import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import test from 'node:test';

const PACKAGING_ROOT = process.cwd();

test('Windows tray controller exposes required notification-area menu', () => {
  const script = readFileSync(join(PACKAGING_ROOT, 'windows', 'office-mcp-tray.ps1'), 'utf8');
  const repoRoot = join(PACKAGING_ROOT, '..');
  const rustTrayHost = readFileSync(join(repoRoot, 'src', 'office-mcp', 'daemon', 'src', 'tray', 'native_tray.rs'), 'utf8');
  const rustTrayController = readFileSync(join(repoRoot, 'src', 'office-mcp', 'daemon', 'src', 'tray', 'controller.rs'), 'utf8');
  const rustTrayModel = readFileSync(join(repoRoot, 'src', 'office-mcp', 'daemon', 'src', 'tray', 'model.rs'), 'utf8');

  assert.match(script, /office-mcp-daemon\.exe/);
  assert.match(script, /"tray"/);
  assert.match(script, /--probe/);
  assert.match(rustTrayHost, /tray_icon::/);
  assert.match(rustTrayHost, /tao::event_loop/);
  assert.match(rustTrayHost, /MenuItem::with_id/);
  assert.match(rustTrayHost, /office-mcp-show/);
  assert.match(rustTrayHost, /office-mcp-quit/);
  assert.match(rustTrayController, /snapshot_from_ui_state/);
  assert.match(rustTrayModel, /Status:/);
  assert.match(rustTrayModel, /Clients:/);
  assert.match(rustTrayModel, /Documents:/);
  assert.match(rustTrayModel, /current_tasks/);
  assert.match(rustTrayModel, /Show Office MCP Control/);
  assert.match(rustTrayModel, /Quit Office MCP Control/);
  assert.match(rustTrayModel, /Keep Running/);
  assert.match(rustTrayModel, /running tasks/);
  assert.doesNotMatch(script, /node\.exe/);
  assert.doesNotMatch(script, /reference-node/);
  assert.doesNotMatch(script, /dist\src\cli\.js/);
  assert.doesNotMatch(script, /System\.Windows\.Forms\.NotifyIcon/);
  assert.doesNotMatch(script, /ContextMenuStrip/);
  assert.doesNotMatch(script, new RegExp(['x-office-mcp-ui', 'token'].join('-'), 'i'));
  assert.doesNotMatch(script, new RegExp(['ui', 'Token'].join('')));
  assert.doesNotMatch(script, /Start-ScheduledTask/);
});

test('Windows packaging includes the tray controller and simplified portable payload', () => {
  const buildScript = readFileSync(join(PACKAGING_ROOT, 'windows', 'build-windows-portable.ps1'), 'utf8');
  const installScript = readFileSync(join(PACKAGING_ROOT, 'windows', 'install-windows.ps1'), 'utf8');
  const repoRoot = join(PACKAGING_ROOT, '..');
  const icon32 = readFileSync(join(repoRoot, 'src', 'office-ctl', 'common', 'assets', 'icon-32.png'));
  const icon80 = readFileSync(join(repoRoot, 'src', 'office-ctl', 'common', 'assets', 'icon-80.png'));

  assert.match(buildScript, /cargo build --release -p office-mcp-daemon/);
  assert.match(buildScript, /office-mcp-daemon\.exe/);
  assert.match(buildScript, /\$uiRoot = Join-Path \$rustDaemonRoot "src\\ui\\assets"/);
  assert.doesNotMatch(buildScript, /\$uiRoot = Join-Path \$repoRoot "src\\office-mcp\\ui"/);
  assert.match(buildScript, /office-mcp\\ui\\index\.html/);
  assert.match(buildScript, /office-ctl\\common\\addin-channel\.js/);
  assert.match(buildScript, /office-ctl\\common\\browser-ui\.js/);
  assert.match(buildScript, /office-ctl\\common\\logger\.js/);
  assert.match(buildScript, /office-ctl\\common\\task-history\.js/);
  assert.match(buildScript, /office-ctl\\common\\assets\\brand-mark\.svg/);
  assert.match(buildScript, /office-ctl\\common\\assets\\icon-32\.png/);
  assert.match(buildScript, /office-ctl\\common\\assets\\icon-80\.png/);
  assert.match(buildScript, /brand-mark\.svg/);
  assert.match(buildScript, /office-ctl\\excel\\manifest\.xml/);
  assert.match(buildScript, /office-ctl\\excel\\public\\taskpane\.js/);
  assert.match(buildScript, /office-ctl\\powerpoint\\manifest\.xml/);
  assert.match(buildScript, /office-ctl\\powerpoint\\public\\taskpane\.js/);
  assert.match(buildScript, /Push-Location \$powerPointAddinRoot[\s\S]*npm ci[\s\S]*npm run check/);
  assert.match(buildScript, /addin-catalog\\office-mcp-word\.xml/);
  assert.match(buildScript, /addin-catalog\\office-mcp-excel\.xml/);
  assert.match(buildScript, /addin-catalog\\office-mcp-powerpoint\.xml/);
  assert.match(buildScript, /register-office-catalog\.ps1/);
  assert.match(buildScript, /-CatalogPath \$stageCatalogRoot/);
  assert.doesNotMatch(buildScript, /Destination \(Join-Path \$stageCatalogRoot "office-mcp-word\.xml"\)/);
  assert.doesNotMatch(buildScript, /Destination \(Join-Path \$stageCatalogRoot "office-mcp-excel\.xml"\)/);
  assert.doesNotMatch(buildScript, /Destination \(Join-Path \$stageCatalogRoot "office-mcp-powerpoint\.xml"\)/);
  assert.match(buildScript, /scripts\\export-localhost-dev-cert\.ps1/);
  assert.match(buildScript, /install\.ps1/);
  assert.match(buildScript, /uninstall\.ps1/);
  assert.match(buildScript, /Start-Process[\s\S]*office-mcp-daemon\.exe|\$daemonExe[\s\S]*Start-Process/);
  assert.match(buildScript, /ArgumentList 'daemon', 'run'/);
  assert.match(buildScript, /WindowStyle Hidden/);
  assert.doesNotMatch(buildScript, /office-mcp-install-user\.ps1/);
  assert.doesNotMatch(buildScript, /install-user\.ps1/);
  assert.doesNotMatch(buildScript, /uninstall-user\.ps1/);
  assert.doesNotMatch(buildScript, /start-daemon\.ps1/);
  assert.doesNotMatch(buildScript, /Copy-Item[\s\S]*office-mcp-tray\.ps1/);
  assert.doesNotMatch(buildScript, /Set-Content[\s\S]*office-mcp-env\.ps1/);
  assert.doesNotMatch(buildScript, /Set-Content[\s\S]*office-mcp-daemon\.ps1/);
  assert.doesNotMatch(buildScript, /Set-Content[\s\S]*office-mcp\.ps1/);
  assert.match(buildScript, /Portable staging payload must not expose duplicate root launcher/);
  assert.match(buildScript, /OFFICE_MCP_CONFIG_PATH/);
  assert.match(buildScript, /README-install\.txt/);
  assert.match(buildScript, /office-mcp-windows-portable-\$Version-x64\.zip/);
  assert.match(buildScript, /\[string\]\$Version = ""/);
  assert.match(buildScript, /packaging\\package\.json/);
  assert.match(buildScript, /ConvertFrom-Json\)\.version/);
  assert.doesNotMatch(buildScript, /\[string\]\$Version = "0\.1\.7"/);
  assert.match(buildScript, /Compress-Archive/);
  assert.match(buildScript, /portable-stage/);
  assert.doesNotMatch(buildScript, /office-mcp-setup|\.msi|dotnet wix|WiX|Wix|wixpdb/i);
  assert.match(buildScript, /ConvertTo-OfficeCatalogUrl/);
  assert.match(buildScript, /return "\\\\localhost\\\$drive`\$\\\$relativePath"/);
  assert.match(buildScript, /Assert-OfficeHostsClosed/);
  assert.match(buildScript, /Read-Host/);
  assert.match(buildScript, /CloseOfficeHosts/);
  assert.match(buildScript, /NonInteractive/);
  assert.match(buildScript, /Word, Excel, or PowerPoint is running/);
  assert.match(buildScript, /Stop-OfficeMcpDaemons/);
  assert.match(buildScript, /Copy-PortablePayload/);
  assert.match(buildScript, /Remove-LegacyVersionedInstallRoots/);
  assert.match(buildScript, /Remove-StaleOfficeMcpTrustedCatalogs/);
  assert.match(buildScript, /OFFICE_MCP_INSTALL_ROOT/);
  assert.match(buildScript, /\[string\]\$InstallRoot/);
  assert.match(buildScript, /Remove-OfficeAddinCache/);
  assert.match(buildScript, /Remove-CustomUiValidationCache/);
  assert.match(buildScript, /6D178D62-0D2E-4BD6-9F03-5F7FCA34EC57/);
  assert.match(buildScript, /TrustedCatalogs\\\$catalogId/);
  assert.match(buildScript, /TrustedCatalogs\\office-mcp/);
  assert.match(buildScript, /-CreateIfMissing/);
  assert.match(buildScript, /install\.ps1[\s\S]*export-localhost-dev-cert\.ps1[\s\S]*-CreateIfMissing/);
  assert.doesNotMatch(buildScript, /Tray launcher must delegate to the native Rust tray host/);
  assert.doesNotMatch(buildScript, /node\\node\.exe/);
  assert.doesNotMatch(buildScript, /dist\\src\\cli\.js/);
  assert.doesNotMatch(buildScript, /reference-node\\scripts/);
  assert.match(installScript, /office-mcp-tray\.ps1/);
  assert.match(installScript, /cargo build --release -p office-mcp-daemon/);
  assert.match(installScript, /office-mcp-daemon\.exe/);
  assert.match(installScript, /\$uiRoot = Join-Path \$rustDaemonRoot "src\\ui\\assets"/);
  assert.doesNotMatch(installScript, /\$uiRoot = Join-Path \$repoRoot "src\\office-mcp\\ui"/);
  assert.match(installScript, /office-mcp\\ui/);
  assert.match(installScript, /office-ctl\\common/);
  assert.match(installScript, /office-ctl\\word/);
  assert.match(installScript, /office-ctl\\excel/);
  assert.match(installScript, /office-ctl\\powerpoint/);
  assert.match(installScript, /installedWordRoot/);
  assert.match(installScript, /installedPowerPointRoot/);
  assert.match(installScript, /Push-Location \$powerPointAddinRoot[\s\S]*npm ci[\s\S]*npm run check/);
  assert.match(installScript, /register-office-catalog\.ps1/);
  assert.match(installScript, /-CatalogPath \$catalogPath/);
  assert.match(installScript, /-ClearOfficeCache/);
  assert.match(installScript, /\$catalogOutput = & \$catalogScriptPath/);
  assert.match(installScript, /\$catalogScriptPath = Join-Path \$commonRoot "scripts\\register-office-catalog\.ps1"/);
  assert.doesNotMatch(installScript, /Destination \(Join-Path \$catalogPath "office-mcp-word\.xml"\)/);
  assert.doesNotMatch(installScript, /Destination \(Join-Path \$catalogPath "office-mcp-excel\.xml"\)/);
  assert.doesNotMatch(installScript, /Destination \(Join-Path \$catalogPath "office-mcp-powerpoint\.xml"\)/);
  assert.match(installScript, /commonRoot/);
  assert.match(readFileSync(join(repoRoot, 'src', 'office-ctl', 'common', 'scripts', 'register-office-catalog.ps1'), 'utf8'), /6D178D62-0D2E-4BD6-9F03-5F7FCA34EC57|TrustedCatalogs\\office-mcp/);
  assert.doesNotMatch(installScript, /Set-ItemProperty -Path \$catalogKey/);
  assert.match(installScript, /Catalog URL: \$catalogUrl/);
  assert.doesNotMatch(installScript, new RegExp(['npm run', 'daemon'].join(' ')));
  assert.match(installScript, /Tray launcher:/);
  assert.match(installScript, /New-ScheduledTaskAction[\s\S]*office-mcp-daemon\.exe[\s\S]*tray/);
  assert.deepEqual([...icon32.subarray(0, 8)], [137, 80, 78, 71, 13, 10, 26, 10]);
  assert.equal(icon32.readUInt32BE(16), 32);
  assert.equal(icon80.readUInt32BE(16), 80);
});

test('Windows localhost certificate helper lives under packaging', () => {
  const helper = readFileSync(join(PACKAGING_ROOT, 'windows', 'export-localhost-dev-cert.ps1'), 'utf8');

  assert.match(helper, /Cert:\\CurrentUser\\My/);
  assert.match(helper, /Cert:\\CurrentUser\\Root/);
  assert.match(helper, /New-SelfSignedCertificate/);
  assert.match(helper, /CreateIfMissing/);
  assert.match(helper, /Export-PfxCertificate/);
  assert.doesNotMatch(helper, /Import-PfxCertificate/);
});

test('GitHub release workflow publishes only the Windows portable artifacts', () => {
  const repoRoot = join(PACKAGING_ROOT, '..');
  const workflow = readFileSync(join(repoRoot, '.github', 'workflows', 'release.yml'), 'utf8');

  assert.match(workflow, /name:\s*Release/);
  assert.match(workflow, /workflow_dispatch:/);
  assert.match(workflow, /bump:/);
  assert.match(workflow, /type:\s*choice/);
  assert.match(workflow, /options:[\s\S]*patch[\s\S]*minor[\s\S]*major/);
  assert.doesNotMatch(workflow, /target_version|release_version|version:\s*\n\s*description:/i);
  assert.match(workflow, /tags:\s*\[\s*['"]v\*['"]\s*\]/);
  assert.doesNotMatch(workflow, /default:\s*['"]0\.1\.1['"]/);
  assert.match(workflow, /Prepare release version/);
  assert.match(workflow, /needs:\s*prepare-release/);
  assert.match(workflow, /runs-on:\s*windows-latest/);
  assert.match(workflow, /actions\/checkout@v4/);
  assert.match(workflow, /fetch-depth:\s*0/);
  assert.match(workflow, /ref:\s*\$\{\{ needs\.prepare-release\.outputs\.tag \}\}/);
  assert.match(workflow, /github\.event\.inputs\.bump/);
  assert.match(workflow, /ConvertFrom-Json -AsHashtable/);
  assert.match(workflow, /packaging\/package-lock\.json/);
  assert.match(workflow, /Cargo\.lock/);
  assert.match(workflow, /PSNativeCommandUseErrorActionPreference/);
  assert.match(workflow, /git show-ref --tags --verify --quiet "refs\/tags\/\$tag"/);
  assert.match(workflow, /\$localTagExit = \$LASTEXITCODE/);
  assert.match(workflow, /\$remoteTagExit = \$LASTEXITCODE/);
  assert.match(workflow, /git ls-remote --exit-code --tags origin/);
  assert.match(workflow, /Version tag already exists/);
  assert.match(workflow, /"tag=v\$version" >> \$env:GITHUB_OUTPUT\s+exit 0/);
  assert.match(workflow, /"tag=\$tag" >> \$env:GITHUB_OUTPUT\s+exit 0/);
  assert.doesNotMatch(workflow, /"tag=v\$version" >> \$env:GITHUB_OUTPUT\s+return/);
  assert.doesNotMatch(workflow, /if \(git rev-parse/);
  assert.match(workflow, /git commit -m "Release v\$version"/);
  assert.match(workflow, /git push origin HEAD:main/);
  assert.match(workflow, /git tag "v\$version"/);
  assert.match(workflow, /git push origin "v\$version"/);
  assert.ok(workflow.indexOf('git push origin HEAD:main') < workflow.indexOf('git tag "v$version"'));
  assert.ok(!existsSync(join(repoRoot, '.github', 'workflows', 'release-kickoff.yml')));
  assert.match(workflow, /dtolnay\/rust-toolchain@stable/);
  assert.match(workflow, /actions\/setup-node@v4/);
  assert.match(workflow, /working-directory:\s*packaging[\s\S]*npm ci[\s\S]*npm run check/);
  assert.match(workflow, /working-directory:\s*src\/office-mcp\/daemon\/evidence[\s\S]*npm ci/);
  assert.match(workflow, /Run daemon evidence checks/);
  assert.match(workflow, /working-directory:\s*src\/office-mcp\/daemon\/evidence[\s\S]*npm run check/);
  assert.match(workflow, /Generate rendered logo review/);
  assert.match(workflow, /record-rendered-logo-review\.mjs/);
  assert.match(workflow, /logo-rendered-size-review\.json/);
  assert.match(workflow, /logo-rendered-size-review\.png/);
  assert.match(workflow, /Generate catalog identity review/);
  assert.match(workflow, /record-catalog-identity-review\.mjs/);
  assert.match(workflow, /catalog-identity-review\.json/);
  assert.match(workflow, /artifacts\\portable-stage\\addin-catalog/);
  assert.match(workflow, /working-directory:\s*src\/office-ctl\/word[\s\S]*npm ci/);
  assert.match(workflow, /working-directory:\s*src\/office-ctl\/excel[\s\S]*npm ci/);
  assert.match(workflow, /working-directory:\s*src\/office-ctl\/powerpoint[\s\S]*npm ci/);
  assert.match(workflow, /Validate release version metadata/);
  assert.match(workflow, /packaging\/package\.json/);
  assert.match(workflow, /src\/office-mcp\/daemon\/Cargo\.toml/);
  assert.match(workflow, /version mismatch/i);
  assert.match(workflow, /Check PowerShell scripts syntax/);
  assert.match(workflow, /PSParser/);
  assert.match(workflow, /packaging\/windows\/install-windows\.ps1/);
  assert.match(workflow, /packaging\/windows\/build-windows-portable\.ps1/);
  assert.match(workflow, /src\/office-ctl\/common\/scripts\/render-hosted-manifest\.ps1/);
  assert.match(workflow, /src\/office-ctl\/word\/scripts\/render-hosted-manifest\.ps1/);
  assert.match(workflow, /src\/office-ctl\/excel\/scripts\/render-hosted-manifest\.ps1/);
  assert.match(workflow, /src\/office-ctl\/powerpoint\/scripts\/render-hosted-manifest\.ps1/);
  assert.match(workflow, /Run Word add-in checks/);
  assert.match(workflow, /working-directory:\s*src\/office-ctl\/word[\s\S]*npm run check/);
  assert.match(workflow, /Run Excel add-in checks/);
  assert.match(workflow, /working-directory:\s*src\/office-ctl\/excel[\s\S]*npm run check/);
  assert.match(workflow, /Run PowerPoint add-in checks/);
  assert.match(workflow, /working-directory:\s*src\/office-ctl\/powerpoint[\s\S]*npm run check/);
  assert.match(workflow, /Prepare daemon test certificate/);
  assert.match(workflow, /New-SelfSignedCertificate/);
  assert.match(workflow, /src\/office-mcp\/daemon\/\.office-mcp-localhost\.pfx/);
  assert.match(workflow, /Export-PfxCertificate/);
  assert.match(workflow, /Remove-Item -LiteralPath "Cert:\\CurrentUser\\My\\\$\(\$cert\.Thumbprint\)"/);
  assert.match(workflow, /Run daemon tests/);
  assert.match(workflow, /cargo test -p office-mcp-daemon/);
  assert.match(workflow, /build-windows-portable\.ps1 -Version \$\{\{ steps\.version\.outputs\.version \}\} -SkipNpmInstall/);
  assert.match(workflow, /git diff --check/);
  assert.match(workflow, /office-mcp-windows-portable-\$version-x64\.zip/);
  assert.match(workflow, /portable_zip/);
  assert.match(workflow, /README-install\.txt/);
  assert.match(workflow, /install\.ps1/);
  assert.match(workflow, /uninstall\.ps1/);
  assert.match(workflow, /office-mcp\.ps1/);
  assert.match(workflow, /office-mcp-daemon\.ps1/);
  assert.match(workflow, /office-mcp-tray\.ps1/);
  assert.match(workflow, /office-mcp-env\.ps1/);
  assert.match(workflow, /Release payload must not include duplicate root launcher/);
  assert.doesNotMatch(workflow, /install-user\.ps1/);
  assert.doesNotMatch(workflow, /start-daemon\.ps1/);
  assert.doesNotMatch(workflow, /uninstall-user\.ps1/);
  assert.doesNotMatch(workflow, /office-mcp-setup|\.msi|\$\{\{ steps\.stage\.outputs\.msi \}\}/i);
  assert.match(workflow, /SHA256SUMS/);
  assert.match(workflow, /Get-FileHash[\s\S]*Split-Path -Leaf \$releaseZip[\s\S]*logo-rendered-size-review\.json[\s\S]*logo-rendered-size-review\.png[\s\S]*catalog-identity-review\.json/);
  assert.doesNotMatch(workflow, /RELEASE_NOTES\.md/);
  assert.match(workflow, /Get-FileHash/);
  assert.match(workflow, /actions\/upload-artifact@v4/);
  assert.match(workflow, /\$\{\{ steps\.stage\.outputs\.rendered_logo_review \}\}/);
  assert.match(workflow, /\$\{\{ steps\.stage\.outputs\.rendered_logo_sheet \}\}/);
  assert.match(workflow, /\$\{\{ steps\.stage\.outputs\.catalog_identity_review \}\}/);
  assert.match(workflow, /softprops\/action-gh-release@v2/);
  assert.match(workflow, /draft:\s*true/);
  assert.match(workflow, /prerelease:\s*true/);
  assert.doesNotMatch(workflow, /body_path:/);
  assert.match(workflow, /generate_release_notes:\s*true/);
  assert.doesNotMatch(workflow, /github\.ref_type == 'tag'/);
  assert.match(workflow, /startsWith\(needs\.prepare-release\.outputs\.tag, 'v'\)/);
});

test('GitHub CI verifies the Windows portable zip using package metadata version', () => {
  const repoRoot = join(PACKAGING_ROOT, '..');
  const workflow = readFileSync(join(repoRoot, '.github', 'workflows', 'ci.yml'), 'utf8');

  assert.match(workflow, /\$version = \(Get-Content -Raw \.\\packaging\\package\.json \| ConvertFrom-Json\)\.version/);
  assert.match(workflow, /office-mcp-windows-portable-\$version-x64\.zip/);
  assert.doesNotMatch(workflow, /office-mcp-windows-portable-0\.1\.1-x64\.zip/);
});

test('README is a compact landing page with install and MCP config first', () => {
  const repoRoot = join(PACKAGING_ROOT, '..');
  const readme = readFileSync(join(repoRoot, 'README.md'), 'utf8');
  const topLevelHeadings = [...readme.matchAll(/^#{1,2} .+$/gm)].map((match) => match[0].trim());

  assert.deepEqual(topLevelHeadings, [
    '# office-mcp',
    '## Install and MCP config',
    '## Why office-mcp',
    '## Why not just use `python-docx` / `docx2pdf` / COM?',
    '## Architecture (one diagram)',
    '## License',
  ]);
  assert.match(readme, /\[!\[License: MIT\]/);
  assert.match(readme, /\[!\[Release\]/);
  assert.match(readme, /\[!\[Release workflow\]/);
  assert.match(readme, /\[!\[Platform\]/);
  assert.match(
    readme,
    /connects MCP clients to live Microsoft Office documents through Office add-ins and a local MCP daemon/i,
  );
  assert.match(readme, /irm https:\/\/raw\.githubusercontent\.com\/r12f\/office-mcp\/main\/scripts\/install\.ps1 \| iex/);
  assert.match(readme, /http:\/\/127\.0\.0\.1:8800\/mcp/);
  assert.match(readme, /Streamable HTTP endpoint/i);
  assert.match(readme, /the document the user is actually editing/i);
  assert.match(readme, /protected, open, locked, or host-managed/i);
  assert.match(readme, /inside the Office host/i);
  assert.match(readme, /python-docx/);
  assert.match(readme, /docx2pdf/);
  assert.match(readme, /openpyxl/);
  assert.match(readme, /python-pptx/);
  assert.match(readme, /IRM \/ RMS protected documents/);
  assert.match(readme, /Live editing in the user's open document/);
  assert.match(readme, /Office instance exclusive-access errors/);
  assert.match(readme, /MCP client config churn/);
  assert.match(readme, /One persistent local Streamable HTTP endpoint/);
  assert.match(readme, /Windows desktop v1/);
  assert.match(readme, /MCP Client/);
  assert.match(readme, /office-mcp daemon/);
  assert.match(readme, /Word instance A \(add-in\)/);
  assert.match(readme, /Excel instance C \(add-in\)/);
  assert.match(readme, /MCP daemon\*\* is a single long-running process/);
  assert.match(readme, /Office add-ins\*\* are Office\.js task-pane add-ins/);
  assert.match(readme, /Clients\*\* see a uniform MCP tool surface/);
  assert.match(readme, /filters disabled tools/i);
  assert.match(readme, /routes each call to the add-in that owns the target document/i);
  assert.match(readme, /\[MIT\]\(LICENSE\)/);
  assert.match(readme, /\[deployment spec\]\(doc\/spec\/07-deployment\.md\)/i);
  assert.doesNotMatch(readme, /office-mcp-setup|\.msi|MSI/i);
  assert.doesNotMatch(readme, /^## Status$/m);
  assert.doesNotMatch(readme, /^## Verification$/m);
  assert.doesNotMatch(readme, /^## Repository layout$/m);
  assert.doesNotMatch(readme, /^## Run the MVP locally$/m);
});
