import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import test from 'node:test';

const PACKAGING_ROOT = process.cwd();

test('Windows tray controller exposes required notification-area menu', () => {
  const script = readFileSync(join(PACKAGING_ROOT, 'windows', 'office-mcp-tray.ps1'), 'utf8');
  const repoRoot = join(PACKAGING_ROOT, '..');
  const rustTrayHost = readFileSync(join(repoRoot, 'src', 'office-mcp', 'daemon', 'src', 'tray', 'native_tray.rs'), 'utf8');
  const rustTrayController = readFileSync(join(repoRoot, 'src', 'office-mcp', 'daemon', 'src', 'tray', 'controller.rs'), 'utf8');
  const rustTrayModel = readFileSync(join(repoRoot, 'src', 'office-mcp', 'daemon', 'src', 'tray', 'model.rs'), 'utf8');

  assert.match(script, /office-mcp-daemon\.exe/);
  assert.match(script, /"tray"/);
  assert.match(script, /--probe/);
  assert.match(rustTrayHost, /tray_icon::/);
  assert.match(rustTrayHost, /tao::event_loop/);
  assert.match(rustTrayHost, /MenuItem::with_id/);
  assert.match(rustTrayHost, /office-mcp-show/);
  assert.match(rustTrayHost, /office-mcp-quit/);
  assert.match(rustTrayController, /snapshot_from_ui_state/);
  assert.match(rustTrayModel, /Status:/);
  assert.match(rustTrayModel, /Clients:/);
  assert.match(rustTrayModel, /Documents:/);
  assert.match(rustTrayModel, /current_tasks/);
  assert.match(rustTrayModel, /Show Office MCP Control/);
  assert.match(rustTrayModel, /Quit Office MCP Control/);
  assert.match(rustTrayModel, /Keep Running/);
  assert.match(rustTrayModel, /running tasks/);
  assert.doesNotMatch(script, /node\.exe/);
  assert.doesNotMatch(script, /reference-node/);
  assert.doesNotMatch(script, /dist\src\cli\.js/);
  assert.doesNotMatch(script, /System\.Windows\.Forms\.NotifyIcon/);
  assert.doesNotMatch(script, /ContextMenuStrip/);
  assert.doesNotMatch(script, new RegExp(['x-office-mcp-ui', 'token'].join('-'), 'i'));
  assert.doesNotMatch(script, new RegExp(['ui', 'Token'].join('')));
  assert.doesNotMatch(script, /Start-ScheduledTask/);
});

test('Windows packaging includes the tray controller and simplified portable payload', () => {
  const buildScript = readFileSync(join(PACKAGING_ROOT, 'windows', 'build-windows-portable.ps1'), 'utf8');
  const installScript = readFileSync(join(PACKAGING_ROOT, 'windows', 'install-windows.ps1'), 'utf8');
  const repoRoot = join(PACKAGING_ROOT, '..');
  const icon32 = readFileSync(join(repoRoot, 'src', 'office-ctl', 'common', 'assets', 'icon-32.png'));
  const icon80 = readFileSync(join(repoRoot, 'src', 'office-ctl', 'common', 'assets', 'icon-80.png'));

  assert.match(buildScript, /cargo build --release -p office-mcp-daemon/);
  assert.match(buildScript, /office-mcp-daemon\.exe/);
  assert.match(buildScript, /\$uiRoot = Join-Path \$rustDaemonRoot "src\\ui\\assets"/);
  assert.doesNotMatch(buildScript, /\$uiRoot = Join-Path \$repoRoot "src\\office-mcp\\ui"/);
  assert.match(buildScript, /office-mcp\\ui\\index\.html/);
  assert.match(buildScript, /office-ctl\\common\\addin-channel\.js/);
  assert.match(buildScript, /office-ctl\\common\\browser-ui\.js/);
  assert.match(buildScript, /office-ctl\\common\\logger\.js/);
  assert.match(buildScript, /office-ctl\\common\\task-history\.js/);
  assert.match(buildScript, /office-ctl\\common\\assets\\brand-mark\.svg/);
  assert.match(buildScript, /office-ctl\\common\\assets\\icon-32\.png/);
  assert.match(buildScript, /office-ctl\\common\\assets\\icon-80\.png/);
  assert.match(buildScript, /brand-mark\.svg/);
  assert.match(buildScript, /office-ctl\\excel\\manifest\.xml/);
  assert.match(buildScript, /office-ctl\\excel\\public\\taskpane\.js/);
  assert.match(buildScript, /office-ctl\\powerpoint\\manifest\.xml/);
  assert.match(buildScript, /office-ctl\\powerpoint\\public\\taskpane\.js/);
  assert.match(buildScript, /Push-Location \$powerPointAddinRoot[\s\S]*npm ci[\s\S]*npm run check/);
  assert.match(buildScript, /addin-catalog\\office-mcp-word\.xml/);
  assert.match(buildScript, /addin-catalog\\office-mcp-excel\.xml/);
  assert.match(buildScript, /addin-catalog\\office-mcp-powerpoint\.xml/);
  assert.match(buildScript, /register-office-catalog\.ps1/);
  assert.match(buildScript, /-CatalogPath \$stageCatalogRoot/);
  assert.doesNotMatch(buildScript, /Destination \(Join-Path \$stageCatalogRoot "office-mcp-word\.xml"\)/);
  assert.doesNotMatch(buildScript, /Destination \(Join-Path \$stageCatalogRoot "office-mcp-excel\.xml"\)/);
  assert.doesNotMatch(buildScript, /Destination \(Join-Path \$stageCatalogRoot "office-mcp-powerpoint\.xml"\)/);
  assert.match(buildScript, /scripts\\export-localhost-dev-cert\.ps1/);
  assert.match(buildScript, /install\.ps1/);
  assert.match(buildScript, /uninstall\.ps1/);
  assert.match(buildScript, /Start-Process[\s\S]*office-mcp-daemon\.exe|\$daemonExe[\s\S]*Start-Process/);
  assert.match(buildScript, /ArgumentList 'tray'/);
  assert.match(buildScript, /WindowStyle Hidden/);
  assert.doesNotMatch(buildScript, /office-mcp-install-user\.ps1/);
  assert.doesNotMatch(buildScript, /install-user\.ps1/);
  assert.doesNotMatch(buildScript, /uninstall-user\.ps1/);
  assert.doesNotMatch(buildScript, /start-daemon\.ps1/);
  assert.doesNotMatch(buildScript, /Copy-Item[\s\S]*office-mcp-tray\.ps1/);
  assert.doesNotMatch(buildScript, /Set-Content[\s\S]*office-mcp-env\.ps1/);
  assert.doesNotMatch(buildScript, /Set-Content[\s\S]*office-mcp-daemon\.ps1/);
  assert.doesNotMatch(buildScript, /Set-Content[\s\S]*office-mcp\.ps1/);
  assert.match(buildScript, /Portable staging payload must not expose duplicate root launcher/);
  assert.match(buildScript, /OFFICE_MCP_CONFIG_PATH/);
  assert.match(buildScript, /README-install\.txt/);
  assert.match(buildScript, /office-mcp-windows-portable-\$Version-x64\.zip/);
  assert.match(buildScript, /Compress-Archive/);
  assert.match(buildScript, /portable-stage/);
  assert.doesNotMatch(buildScript, /office-mcp-setup|\.msi|dotnet wix|WiX|Wix|wixpdb/i);
  assert.match(buildScript, /ConvertTo-OfficeCatalogUrl/);
  assert.match(buildScript, /return "\\\\localhost\\\$drive`\$\\\$relativePath"/);
  assert.match(buildScript, /6D178D62-0D2E-4BD6-9F03-5F7FCA34EC57/);
  assert.match(buildScript, /TrustedCatalogs\\\$catalogId/);
  assert.match(buildScript, /TrustedCatalogs\\office-mcp/);
  assert.match(buildScript, /-CreateIfMissing/);
  assert.match(buildScript, /install\.ps1[\s\S]*export-localhost-dev-cert\.ps1[\s\S]*-CreateIfMissing/);
  assert.doesNotMatch(buildScript, /Tray launcher must delegate to the native Rust tray host/);
  assert.doesNotMatch(buildScript, /node\\node\.exe/);
  assert.doesNotMatch(buildScript, /dist\\src\\cli\.js/);
  assert.doesNotMatch(buildScript, /reference-node\\scripts/);
  assert.match(installScript, /office-mcp-tray\.ps1/);
  assert.match(installScript, /cargo build --release -p office-mcp-daemon/);
  assert.match(installScript, /office-mcp-daemon\.exe/);
  assert.match(installScript, /\$uiRoot = Join-Path \$rustDaemonRoot "src\\ui\\assets"/);
  assert.doesNotMatch(installScript, /\$uiRoot = Join-Path \$repoRoot "src\\office-mcp\\ui"/);
  assert.match(installScript, /office-mcp\\ui/);
  assert.match(installScript, /office-ctl\\common/);
  assert.match(installScript, /office-ctl\\word/);
  assert.match(installScript, /office-ctl\\excel/);
  assert.match(installScript, /office-ctl\\powerpoint/);
  assert.match(installScript, /installedWordRoot/);
  assert.match(installScript, /installedPowerPointRoot/);
  assert.match(installScript, /Push-Location \$powerPointAddinRoot[\s\S]*npm ci[\s\S]*npm run check/);
  assert.match(installScript, /register-office-catalog\.ps1/);
  assert.match(installScript, /-CatalogPath \$catalogPath/);
  assert.match(installScript, /-ClearOfficeCache/);
  assert.match(installScript, /\$catalogScriptPath = Join-Path \$commonRoot "scripts\\register-office-catalog\.ps1"/);
  assert.doesNotMatch(installScript, /Destination \(Join-Path \$catalogPath "office-mcp-word\.xml"\)/);
  assert.doesNotMatch(installScript, /Destination \(Join-Path \$catalogPath "office-mcp-excel\.xml"\)/);
  assert.doesNotMatch(installScript, /Destination \(Join-Path \$catalogPath "office-mcp-powerpoint\.xml"\)/);
  assert.match(installScript, /commonRoot/);
  assert.match(installScript, /function ConvertTo-OfficeCatalogUrl/);
  assert.match(installScript, /\\\\localhost/);
  assert.match(installScript, /6D178D62-0D2E-4BD6-9F03-5F7FCA34EC57|TrustedCatalogs\\office-mcp/);
  assert.match(installScript, /-Name Url -Value \$catalogUrl/);
  assert.match(installScript, /Catalog URL: \$catalogUrl/);
  assert.doesNotMatch(installScript, new RegExp(['npm run', 'daemon'].join(' ')));
  assert.match(installScript, /Tray launcher:/);
  assert.match(installScript, /New-ScheduledTaskAction[\s\S]*office-mcp-daemon\.exe[\s\S]*tray/);
  assert.deepEqual([...icon32.subarray(0, 8)], [137, 80, 78, 71, 13, 10, 26, 10]);
  assert.equal(icon32.readUInt32BE(16), 32);
  assert.equal(icon80.readUInt32BE(16), 80);
});

test('Windows localhost certificate helper lives under packaging', () => {
  const helper = readFileSync(join(PACKAGING_ROOT, 'windows', 'export-localhost-dev-cert.ps1'), 'utf8');

  assert.match(helper, /Cert:\\CurrentUser\\My/);
  assert.match(helper, /Cert:\\CurrentUser\\Root/);
  assert.match(helper, /New-SelfSignedCertificate/);
  assert.match(helper, /CreateIfMissing/);
  assert.match(helper, /Export-PfxCertificate/);
  assert.doesNotMatch(helper, /Import-PfxCertificate/);
});

test('GitHub release workflow publishes only the Windows portable artifacts', () => {
  const repoRoot = join(PACKAGING_ROOT, '..');
  const workflow = readFileSync(join(repoRoot, '.github', 'workflows', 'release.yml'), 'utf8');

  assert.match(workflow, /name:\s*Release/);
  assert.match(workflow, /workflow_dispatch:/);
  assert.match(workflow, /tags:\s*\[\s*['"]v\*['"]\s*\]/);
  assert.match(workflow, /runs-on:\s*windows-latest/);
  assert.match(workflow, /actions\/checkout@v4/);
  assert.match(workflow, /dtolnay\/rust-toolchain@stable/);
  assert.match(workflow, /actions\/setup-node@v4/);
  assert.match(workflow, /working-directory:\s*packaging[\s\S]*npm ci[\s\S]*npm run check/);
  assert.match(workflow, /working-directory:\s*src\/office-mcp\/daemon\/evidence[\s\S]*npm ci/);
  assert.match(workflow, /Run daemon evidence checks/);
  assert.match(workflow, /working-directory:\s*src\/office-mcp\/daemon\/evidence[\s\S]*npm run check/);
  assert.match(workflow, /Generate rendered logo review/);
  assert.match(workflow, /record-rendered-logo-review\.mjs/);
  assert.match(workflow, /logo-rendered-size-review\.json/);
  assert.match(workflow, /logo-rendered-size-review\.png/);
  assert.match(workflow, /Generate catalog identity review/);
  assert.match(workflow, /record-catalog-identity-review\.mjs/);
  assert.match(workflow, /catalog-identity-review\.json/);
  assert.match(workflow, /artifacts\\portable-stage\\addin-catalog/);
  assert.match(workflow, /working-directory:\s*src\/office-ctl\/word[\s\S]*npm ci/);
  assert.match(workflow, /working-directory:\s*src\/office-ctl\/excel[\s\S]*npm ci/);
  assert.match(workflow, /working-directory:\s*src\/office-ctl\/powerpoint[\s\S]*npm ci/);
  assert.match(workflow, /Validate release version metadata/);
  assert.match(workflow, /packaging\/package\.json/);
  assert.match(workflow, /src\/office-mcp\/daemon\/Cargo\.toml/);
  assert.match(workflow, /version mismatch/i);
  assert.match(workflow, /Check PowerShell scripts syntax/);
  assert.match(workflow, /PSParser/);
  assert.match(workflow, /packaging\/windows\/install-windows\.ps1/);
  assert.match(workflow, /packaging\/windows\/build-windows-portable\.ps1/);
  assert.match(workflow, /src\/office-ctl\/common\/scripts\/render-hosted-manifest\.ps1/);
  assert.match(workflow, /src\/office-ctl\/word\/scripts\/render-hosted-manifest\.ps1/);
  assert.match(workflow, /src\/office-ctl\/excel\/scripts\/render-hosted-manifest\.ps1/);
  assert.match(workflow, /src\/office-ctl\/powerpoint\/scripts\/render-hosted-manifest\.ps1/);
  assert.match(workflow, /Run Word add-in checks/);
  assert.match(workflow, /working-directory:\s*src\/office-ctl\/word[\s\S]*npm run check/);
  assert.match(workflow, /Run Excel add-in checks/);
  assert.match(workflow, /working-directory:\s*src\/office-ctl\/excel[\s\S]*npm run check/);
  assert.match(workflow, /Run PowerPoint add-in checks/);
  assert.match(workflow, /working-directory:\s*src\/office-ctl\/powerpoint[\s\S]*npm run check/);
  assert.match(workflow, /Prepare daemon test certificate/);
  assert.match(workflow, /New-SelfSignedCertificate/);
  assert.match(workflow, /src\/office-mcp\/daemon\/\.office-mcp-localhost\.pfx/);
  assert.match(workflow, /Export-PfxCertificate/);
  assert.match(workflow, /Remove-Item -LiteralPath "Cert:\\CurrentUser\\My\\\$\(\$cert\.Thumbprint\)"/);
  assert.match(workflow, /Run daemon tests/);
  assert.match(workflow, /cargo test -p office-mcp-daemon/);
  assert.match(workflow, /build-windows-portable\.ps1 -Version \$\{\{ steps\.version\.outputs\.version \}\} -SkipNpmInstall/);
  assert.match(workflow, /git diff --check/);
  assert.match(workflow, /office-mcp-windows-portable-\$version-x64\.zip/);
  assert.match(workflow, /portable_zip/);
  assert.match(workflow, /README-install\.txt/);
  assert.match(workflow, /install\.ps1/);
  assert.match(workflow, /uninstall\.ps1/);
  assert.match(workflow, /office-mcp\.ps1/);
  assert.match(workflow, /office-mcp-daemon\.ps1/);
  assert.match(workflow, /office-mcp-tray\.ps1/);
  assert.match(workflow, /office-mcp-env\.ps1/);
  assert.match(workflow, /Release payload must not include duplicate root launcher/);
  assert.doesNotMatch(workflow, /install-user\.ps1/);
  assert.doesNotMatch(workflow, /start-daemon\.ps1/);
  assert.doesNotMatch(workflow, /uninstall-user\.ps1/);
  assert.doesNotMatch(workflow, /office-mcp-setup|\.msi|\$\{\{ steps\.stage\.outputs\.msi \}\}/i);
  assert.match(workflow, /SHA256SUMS/);
  assert.match(workflow, /Get-FileHash[\s\S]*Split-Path -Leaf \$releaseZip[\s\S]*logo-rendered-size-review\.json[\s\S]*logo-rendered-size-review\.png[\s\S]*catalog-identity-review\.json/);
  assert.match(workflow, /RELEASE_NOTES\.md/);
  assert.match(workflow, /Get-FileHash/);
  assert.match(workflow, /actions\/upload-artifact@v4/);
  assert.match(workflow, /\$\{\{ steps\.stage\.outputs\.rendered_logo_review \}\}/);
  assert.match(workflow, /\$\{\{ steps\.stage\.outputs\.rendered_logo_sheet \}\}/);
  assert.match(workflow, /\$\{\{ steps\.stage\.outputs\.catalog_identity_review \}\}/);
  assert.match(workflow, /softprops\/action-gh-release@v2/);
  assert.match(workflow, /draft:\s*true/);
  assert.match(workflow, /prerelease:\s*true/);
  assert.match(workflow, /body_path:\s*RELEASE_NOTES\.md/);
  assert.match(workflow, /github\.ref_type == 'tag'/);
});

test('README documents installation from GitHub Releases', () => {
  const repoRoot = join(PACKAGING_ROOT, '..');
  const readme = readFileSync(join(repoRoot, 'README.md'), 'utf8');
  const installHeading = readme.indexOf('## Install from GitHub Releases');
  const developerHeading = readme.indexOf('## Run the MVP locally');

  assert.ok(installHeading !== -1, 'README must have a user install section');
  assert.ok(developerHeading !== -1, 'README must keep the developer setup section');
  assert.ok(installHeading < developerHeading, 'user install instructions must come before source checkout instructions');
  assert.match(readme, /Windows desktop/i);
  assert.match(readme, /GitHub Releases/);
  assert.match(readme, /office-mcp-windows-portable-<ver>-x64\.zip/);
  assert.doesNotMatch(readme, /office-mcp-setup|\.msi|MSI/i);
  assert.match(readme, /README-install\.txt/);
  assert.match(readme, /powershell -NoProfile -ExecutionPolicy Bypass -File \.\\install\.ps1/);
  assert.match(readme, /install\.ps1/);
  assert.match(readme, /uninstall\.ps1/);
  assert.match(readme, /office-mcp-daemon\.exe config claude-desktop --installed --install-root <extracted-folder>/);
  assert.doesNotMatch(readme, /install-user\.ps1/);
  assert.doesNotMatch(readme, /start-daemon\.ps1/);
  assert.doesNotMatch(readme, /uninstall-user\.ps1/);
  assert.doesNotMatch(readme, /\.\\office-mcp\.ps1/);
  assert.match(readme, /6D178D62-0D2E-4BD6-9F03-5F7FCA34EC57/);
  assert.match(readme, /SHA256SUMS/);
  assert.match(readme, /%LOCALAPPDATA%\\office-mcp\\/);
  assert.match(readme, /tray/i);
  assert.match(readme, /office-mcp-daemon ui/);
  assert.match(readme, /daemon status/);
  assert.match(readme, /Shared Folder/);
  assert.match(readme, /Office MCP Control/);
  assert.match(readme, /http:\/\/127\.0\.0\.1:8800\/mcp/);
  assert.match(readme, /log/i);
  assert.match(readme, /uninstall/i);
});

test('Release notes document the Windows portable pre-release gate', () => {
  const repoRoot = join(PACKAGING_ROOT, '..');
  const releaseNotes = readFileSync(join(repoRoot, 'RELEASE_NOTES.md'), 'utf8');

  assert.match(releaseNotes, /# Release Notes/);
  assert.match(releaseNotes, /## 0\.1\.1/);
  assert.doesNotMatch(releaseNotes, /office-mcp-setup|\.msi|MSI/i);
  assert.match(releaseNotes, /office-mcp-windows-portable-0\.1\.1-x64\.zip/);
  assert.match(releaseNotes, /README-install\.txt/);
  assert.match(releaseNotes, /install\.ps1/);
  assert.match(releaseNotes, /uninstall\.ps1/);
  assert.doesNotMatch(releaseNotes, /install-user\.ps1/);
  assert.doesNotMatch(releaseNotes, /start-daemon\.ps1/);
  assert.doesNotMatch(releaseNotes, /uninstall-user\.ps1/);
  assert.match(releaseNotes, /SHA256SUMS/);
  assert.match(releaseNotes, /unsigned/i);
  assert.match(releaseNotes, /draft/i);
  assert.match(releaseNotes, /pre-release/i);
  assert.match(releaseNotes, /Windows desktop/i);
  assert.match(releaseNotes, /Office MCP Control/);
  assert.match(releaseNotes, /tray evidence/i);
  assert.match(releaseNotes, /portable package smoke evidence/i);
  assert.match(releaseNotes, /live Office evidence/i);
});
