import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import test from 'node:test';

const ADDIN_ROOT = process.cwd();

test('Excel add-in manifest targets workbook host and versioned task pane', () => {
  const manifest = readFileSync(join(ADDIN_ROOT, 'manifest.xml'), 'utf8');
  const html = readFileSync(join(ADDIN_ROOT, 'public', 'taskpane.html'), 'utf8');
  const js = readFileSync(join(ADDIN_ROOT, 'public', 'taskpane.js'), 'utf8');

  assert.match(manifest, /<Host Name="Workbook" \/>/);
  assert.match(manifest, /<Set Name="ExcelApi" MinVersion="1\.1" \/>/);
  assert.match(manifest, /<Version>1\.0\.0\.11<\/Version>/);
  assert.match(manifest, /excel\/taskpane\.html\?v=0\.1\.11/);
  assert.match(html, /common\/taskpane\.css\?v=0\.1\.11/);
  assert.match(html, /common\/addin-channel\.js\?v=0\.1\.11/);
  assert.match(html, /excel\/taskpane\.js\?v=0\.1\.11/);
  assert.match(html, /<script src="https:\/\/appsforoffice\.microsoft\.com\/lib\/1\/hosted\/office\.js"><\/script>/);
  assert.doesNotMatch(html, /<script async src="https:\/\/appsforoffice\.microsoft\.com\/lib\/1\/hosted\/office\.js"><\/script>/);
  assert.match(js, /ADDIN_VERSION = '0\.1\.11'/);
});

test('Excel add-in uses product identity metadata and generated icon URLs', () => {
  const manifest = readFileSync(join(ADDIN_ROOT, 'manifest.xml'), 'utf8');
  const html = readFileSync(join(ADDIN_ROOT, 'public', 'taskpane.html'), 'utf8');

  assert.match(manifest, /<ProviderName>Office MCP Control<\/ProviderName>/);
  assert.match(manifest, /<DisplayName DefaultValue="Office MCP Control" \/>/);
  assert.match(manifest, /Control live Excel workbooks through a local productivity automation control utility\./);
  assert.match(manifest, /<bt:String id="OfficeMcp\.GroupLabel" DefaultValue="Office MCP Control" \/>/);
  assert.match(manifest, /<bt:String id="OfficeMcp\.OpenPane\.Label" DefaultValue="Open Control Panel" \/>/);
  assert.match(manifest, /Office MCP Control for this workbook/);
  assert.match(manifest, /https:\/\/localhost:8765\/assets\/icon-32\.png/);
  assert.match(manifest, /https:\/\/localhost:8765\/assets\/icon-80\.png/);
  assert.doesNotMatch(manifest, /DefaultValue="office-mcp(?: for Excel)?"/);
  assert.doesNotMatch(manifest, /DefaultValue="Open"/);
  assert.match(html, /<title>Office MCP Control<\/title>/);
  assert.match(html, /<img class="product-mark" src="\/assets\/icon-32\.png" width="32" height="32" alt="" aria-hidden="true" \/>/);
  assert.match(html, /<h1>Office MCP Control<\/h1>/);
});

test('Excel task pane uses common channel and registers Excel runtime metadata', () => {
  const html = readFileSync(join(ADDIN_ROOT, 'public', 'taskpane.html'), 'utf8');
  const css = readFileSync(join(ADDIN_ROOT, '..', 'common', 'taskpane.css'), 'utf8');
  const js = readFileSync(join(ADDIN_ROOT, 'public', 'taskpane.js'), 'utf8');

  assert.match(html, /id="connectionBadge"/);
  assert.match(html, /id="runtimeVersions"/);
  assert.match(html, /id="serverVersion"/);
  assert.match(html, /id="protocolVersion"/);
  assert.match(html, /<dd id="runtimeVersions"><span id="serverVersion">Server Unknown<\/span> \/ <span id="protocolVersion">Protocol 1\.0<\/span><\/dd>/);
  assert.match(html, /id="hostPlatform"/);
  assert.match(html, /<dd id="protection">Not protected<\/dd>/);
  assert.match(html, /<dd id="documentState">Editable<\/dd>/);
  assert.match(html, /class="metadata-copy" data-copy-target="session" aria-label="Copy session ID" title="Copy session ID"/);
  assert.match(html, /class="daemon-endpoint-input" name="daemonEndpoint" type="url" inputmode="url" autocomplete="off" spellcheck="false" aria-label="Daemon endpoint"/);
  assert.match(html, /id="historyList"/);
  assert.match(html, /class="panel summary-panel"/);
  assert.match(html, /class="tools-panel"/);
  assert.match(html, /<span>Tools<\/span>/);
  assert.match(html, /id="toolList"/);
  assert.match(html, /Enabled 0 of 0/);
  assert.doesNotMatch(html, /Tool Permissions/);
  assert.doesNotMatch(html, /id="toolPermissionList"/);
  assert.doesNotMatch(html, /id="enabledToolCount"/);
  assert.match(html, /class="daemon-endpoint-input" name="daemonEndpoint" type="url" inputmode="url" autocomplete="off" spellcheck="false" aria-label="Daemon endpoint"/);
  assert.match(html, /id="saveEndpoint" class="icon-button reconnect-button" type="submit" aria-label="Reconnect daemon" title="Reconnect daemon"/);
  assert.doesNotMatch(html, /id="settingsToggle"/);
  assert.doesNotMatch(html, /id="settingsPanel"/);
  assert.doesNotMatch(html, /Save Endpoint/);
  assert.ok(html.indexOf('class="daemon-endpoint-form"') < html.indexOf('id="runtimeVersions"'));
  assert.match(html, /Connecting…/);
  assert.match(html, /placeholder="wss:\/\/localhost:8765\/addin"/);
  assert.doesNotMatch(html, /Connecting\.\.\./);
  assert.doesNotMatch(html, /addin\.\.\./);
  assert.match(readFileSync(join(ADDIN_ROOT, '..', 'common', 'taskpane.css'), 'utf8'), /--accent: #3b6478/);
  assert.match(readFileSync(join(ADDIN_ROOT, 'public', 'taskpane.css'), 'utf8'), /--accent: #217346/);
  assert.match(css, /\.summary-panel/);
  assert.match(css, /\.identity \{[\s\S]*grid-template-columns: 32px minmax\(0, 1fr\);/);
  assert.match(css, /\.product-mark \{[\s\S]*width: 32px;[\s\S]*height: 32px;/);
  assert.match(css, /\.control-glyph \{[\s\S]*width: 18px;[\s\S]*stroke: currentColor;/);
  assert.match(css, /\.tool-list/);
  assert.match(css, /\.daemon-endpoint-form/);
  assert.match(css, /\.reconnect-button/);
  assert.match(css, /\.tool-permission-row/);
  assert.match(css, /\.tool-toggle,\r?\n\.group-toggle/);
  assert.doesNotMatch(css, /is-editing-tools/);
  assert.match(css, /\.metadata-copy \{[\s\S]*display: inline-flex;[\s\S]*min-height: 32px;[\s\S]*text-align: left;/);
  assert.match(css, /\.metadata-copy code \{[\s\S]*overflow-wrap: anywhere;[\s\S]*white-space: normal;/);
  assert.match(css, /\.task-command-id \{[\s\S]*display: flex;[\s\S]*gap: 4px;/);
  assert.match(css, /\.inline-copy \{[\s\S]*display: inline-flex;[\s\S]*min-height: 32px;[\s\S]*background: transparent;[\s\S]*cursor: pointer;/);
  assert.match(css, /\.metadata-copy:hover,[\s\S]*\.inline-copy:focus-visible \{[\s\S]*background: var\(--surface-raised\);/);
  assert.match(css, /prefers-reduced-motion/);
  assert.match(css, /forced-colors: active/);
  assert.match(js, /const TOOL_GROUPS = \[/);
  assert.match(js, /\{ label: 'Data', tools: \['excel\.sort_range', 'excel\.apply_filter'\] \}/);
  assert.match(js, /\{ label: 'Table', tools: \['excel\.create_table', 'excel\.update_table'\] \}/);
  assert.match(js, /\{ label: 'Chart', tools: \['excel\.create_chart', 'excel\.update_chart'\] \}/);
  assert.match(js, /\{ label: 'PivotTable', tools: \['excel\.create_pivot_table', 'excel\.update_pivot_table'\] \}/);
  assert.match(js, /const TOOL_METADATA = new Map\(\[/);
  assert.match(js, /\['excel\.sort_range', \{ category: 'Data', sideEffect: 'mutating'/);
  assert.match(js, /\['excel\.apply_filter', \{ category: 'Data', sideEffect: 'mutating'/);
  assert.match(js, /\['excel\.update_table', \{ category: 'Table', sideEffect: 'destructive'/);
  assert.match(js, /\['excel\.update_chart', \{ category: 'Chart', sideEffect: 'destructive'/);
  assert.match(js, /\['excel\.create_pivot_table', \{ category: 'PivotTable', sideEffect: 'mutating'/);
  assert.match(js, /\['excel\.update_pivot_table', \{ category: 'PivotTable', sideEffect: 'destructive'/);
  assert.match(js, /TOOL_PERMISSION_STORAGE_KEY/);
  assert.match(js, /const toolListEl = document\.getElementById\('toolList'\)/);
  assert.match(js, /function renderToolSummary\(\)/);
  assert.match(js, /toolCountEl\.textContent = `Enabled \$\{effective\.length\} of \$\{AVAILABLE_TOOLS\.length\}`/);
  assert.match(js, /Enabled \$\{enabledInGroup\.length\} of \$\{tools\.length\}/);
  assert.match(js, /renderToolSummary\(\)/);
  assert.match(js, /function toolControlMarkup\(tool\)/);
  assert.doesNotMatch(js, /function renderToolPermissions\(\)/);
  assert.doesNotMatch(js, /toolPermissionListEl/);
  assert.match(js, /function effectiveTools\(\)/);
  assert.match(js, /available_tools: effectiveTools\(\)/);
  assert.match(js, /sessionUpdatedNotification\(\{/);
  assert.match(js, /patch: \{ available_tools: effectiveTools\(\) \}/);
  assert.match(js, /TOOL_DISABLED_BY_USER/);
  assert.match(js, /function isExcelHost\(info\)/);
  assert.match(js, /Office\.HostType\?\.Excel/);
  assert.match(js, /Office\.context\?\.diagnostics\?\.host/);
  assert.match(js, /window\.Excel\?\.run/);
  assert.match(js, /isSetSupported\?\.\('ExcelApi', '1\.1'\)/);
  assert.match(js, /app: 'excel'/);
  assert.match(js, /clearEndpointOverride/);
  assert.match(js, /currentOriginEndpoint/);
  assert.match(js, /function tryCurrentOriginEndpointFallback\(failedEndpoint\)/);
  assert.match(js, /new TaskHistoryStore\(\{ redactText \}\)/);
  assert.match(js, /const \{ history, historyLimit \} = taskStore\.snapshot\(\)/);
  assert.match(js, /historyCountEl\.textContent = `\$\{history\.length\} \/ \$\{historyLimit\}`/);
  assert.match(js, /function taskMarkup\(task\)/);
  assert.match(js, /requestId: currentTask\.requestId/);
  assert.match(js, /class="task-meta task-command-id"/);
  assert.match(js, /aria-label="Copy command ID" title="\$\{escapeHtml\(task\.requestId\)\}"/);
  assert.match(js, /middleTruncate\(task\.requestId\)/);
  assert.match(js, /const requestId = message\.params\?\.request_id \|\| String\(message\.id\)/);
  assert.match(js, /taskStore\.start\(requestId, tool, message\.params \|\| \{\}, message\.params\?\.timeout_ms\)/);
  assert.match(js, /taskStore\.isCancelled\(requestId\)/);
  assert.match(js, /taskStore\.consumeCancellation\(requestId\)/);
  assert.match(js, /function cancelledError\(tool\)/);
  assert.match(js, /userIntent/);
  assert.match(js, /Cancel requested/);
  assert.match(js, /Deadline/);
  assert.match(js, /office_mcp_code/);
  assert.match(js, /Retriable:/);
  assert.match(js, /Partial effect:/);
  assert.match(js, /mapped\.office_mcp_code === 'CANCELLED' \? 'cancelled' : 'failure'/);
  assert.doesNotMatch(js, /Discard unsaved endpoint changes\?/);
  assert.match(js, /Connecting…/);
  assert.match(js, /Reconnecting…/);
  assert.match(js, /Registering…/);
  assert.doesNotMatch(js, /Connecting\.\.\./);
  assert.doesNotMatch(js, /Reconnecting\.\.\./);
  assert.doesNotMatch(js, /Registering\.\.\./);
  assert.doesNotMatch(js, /settingsToggleEl/);
  assert.match(js, /document\.addEventListener\('click', handleMetadataCopy\)/);
  assert.match(js, /async function handleMetadataCopy\(event\)/);
  assert.match(js, /event\.target\.closest\('\[data-copy-target\], \[data-copy-value\]'\)/);
  assert.match(js, /const target = button\.dataset\.copyTarget \? document\.getElementById\(button\.dataset\.copyTarget\) : null/);
  assert.match(js, /const value = button\.dataset\.copyValue \|\| target\?\.textContent\?\.trim\(\)/);
  assert.match(js, /navigator\.clipboard\?\.writeText/);
  assert.match(js, /setCopyableMetadata/);
  assert.match(readFileSync(join(ADDIN_ROOT, '..', 'common', 'main-ui.js'), 'utf8'), /function setCopyableMetadata\(element, value\)/);
  assert.match(js, /middleTruncate/);
  assert.match(readFileSync(join(ADDIN_ROOT, '..', 'common', 'main-ui.js'), 'utf8'), /function middleTruncate\(value, maxLength = 30\)/);
  assert.match(readFileSync(join(ADDIN_ROOT, '..', 'common', 'main-ui.js'), 'utf8'), /return `\$\{text\.slice\(0, head\)\}\$\{marker\}\$\{text\.slice\(text\.length - tail\)\}`/);
  assert.match(js, /function fallbackCopy\(value\)/);
  assert.doesNotMatch(js, /is-editing-tools/);
  assert.doesNotMatch(js, /function activateSettingsWithKeyboard/);
  assert.match(js, /saveEndpointEl\.disabled = true/);
  assert.match(js, /saveEndpointEl\.setAttribute\('aria-busy', 'true'\)/);
  assert.match(js, /renderRuntimeVersions\(serverVersionEl, protocolVersionEl, serverInfo, PROTOCOL_VERSION\)/);
  assert.match(js, /function protectionLabel\(info\)/);
  assert.match(js, /return 'Not protected'/);
  assert.doesNotMatch(js, /protectionEl\.textContent = workbook\.protection\?\.kind \|\| 'Unknown'/);
  assert.match(js, /function documentStateLabel\(info\)/);
  assert.match(js, /return 'Editable'/);
  assert.doesNotMatch(js, /Dirty: \$\{valueLabel/);
  assert.match(js, /registerRequest\(requestId/);
  assert.match(js, /Office\.AutoShowTaskpaneWithDocument/);
  assert.match(js, /function enableAutoOpen\(\)/);
  assert.match(js, /sessionAddedNotification\(\{/);
  assert.match(js, /excel\.get_workbook_info/);
  assert.match(js, /excel\.list_sheets/);
  assert.match(js, /excel\.update_sheet/);
  assert.match(js, /excel\.delete_sheet/);
  assert.match(js, /excel\.get_used_range/);
  assert.match(js, /excel\.clear_range/);
  assert.match(js, /excel\.find_replace_cells/);
  assert.match(js, /excel\.sort_range/);
  assert.match(js, /excel\.apply_filter/);
  assert.match(js, /excel\.update_table/);
  assert.match(js, /excel\.update_chart/);
  assert.match(js, /excel\.create_pivot_table/);
  assert.match(js, /excel\.update_pivot_table/);
  assert.match(js, /case 'excel.get_workbook_info':/);
  assert.match(js, /case 'excel.list_sheets':/);
  assert.match(js, /case 'excel.update_sheet':/);
  assert.match(js, /case 'excel.delete_sheet':/);
  assert.match(js, /case 'excel.get_used_range':/);
  assert.match(js, /case 'excel.clear_range':/);
  assert.match(js, /case 'excel.find_replace_cells':/);
  assert.match(js, /case 'excel.sort_range':/);
  assert.match(js, /case 'excel.apply_filter':/);
  assert.match(js, /case 'excel.update_table':/);
  assert.match(js, /case 'excel.update_chart':/);
  assert.match(js, /case 'excel.create_pivot_table':/);
  assert.match(js, /case 'excel.update_pivot_table':/);
  assert.match(js, /async function getWorkbookInfoTool/);
  assert.match(js, /async function listSheets/);
  assert.match(js, /async function updateSheet/);
  assert.match(js, /async function deleteSheet/);
  assert.match(js, /async function getUsedRange/);
  assert.match(js, /async function clearRange/);
  assert.match(js, /async function findReplaceCells/);
  assert.match(js, /async function sortRange/);
  assert.match(js, /async function applyFilter/);
  assert.match(js, /async function updateTable/);
  assert.match(js, /async function updateChart/);
  assert.match(js, /async function createPivotTable/);
  assert.match(js, /async function updatePivotTable/);
  assert.match(js, /const applyTo = clearApplyToFrom/);
  assert.match(js, /range\.clear\(applyTo\)/);
  assert.match(js, /range\.delete\(deleteShiftDirectionFrom\(deleteShift\)\)/);
  assert.match(js, /const criteria = searchCriteriaFrom\(args\)/);
  assert.match(js, /range\.findOrNullObject\(query, criteria\)/);
  assert.match(js, /range\.replaceAll\(query, replacement, replaceCriteriaFrom/);
  assert.match(js, /requireRequirementSet\('ExcelApi', '1\.2', 'range sorting'\)/);
  assert.match(js, /requireRequirementSet\('ExcelApi', '1\.9', 'range filtering'\)/);
  assert.match(js, /requireRequirementSet\('ExcelApi', '1\.2', 'table filtering'\)/);
  assert.match(js, /requireRequirementSet\('ExcelApi', '1\.13', 'table resize'\)/);
  assert.match(js, /requireRequirementSet\('ExcelApi', '1\.3', 'table visual options'\)/);
  assert.match(js, /requireRequirementSet\('ExcelApi', '1\.7', 'chart axis selection'\)/);
  assert.match(js, /table\.rows\.add\(optionalIndex\(args\.index\), tableValuesFrom\(args\.values, 'rows'\), args\.always_insert !== false\)/);
  assert.match(js, /table\.columns\.add\(optionalIndex\(args\.index\), tableValuesFrom\(args\.values, 'columns'\), optionalName\(args\.name\)\)/);
  assert.match(js, /table\.resize\(requiredString\(args, 'address', 'excel\.update_table resize requires address\.'\)\)/);
  assert.match(js, /table\.name = requiredString\(args, 'name', 'excel\.update_table rename requires name\.'\)/);
  assert.match(js, /applyTableOptions\(table, args\)/);
  assert.match(js, /table\.delete\(\)/);
  assert.match(js, /function tableMetadata\(table, range, bodyRange, headerRange, totalRange\)/);
  assert.match(js, /const headerRange = table\.showHeaders \? table\.getHeaderRowRange\(\) : null/);
  assert.match(js, /const totalRange = table\.showTotals \? table\.getTotalRowRange\(\) : null/);
  assert.match(js, /function applyTableOptions\(table, args\)/);
  assert.match(js, /function tableValuesFrom\(values, label\)/);
  assert.match(js, /function optionalIndex\(value\)/);
  assert.match(js, /function optionalName\(value\)/);
  assert.match(js, /requireRequirementSet\('ExcelApi', '1\.2', 'chart image export'\)/);
  assert.match(js, /const chart = targetChart\(context, args\)/);
  assert.match(js, /chart\.title\.text = requiredString\(args, 'title', 'excel\.update_chart title requires title\.'\)/);
  assert.match(js, /chart\.legend\.position = chartLegendPositionFrom\(args\.position\)/);
  assert.match(js, /chart\.axes\.getItem\(chartAxisTypeFrom\(args\.axis\), chartAxisGroupFrom\(args\.axis_group\)\)/);
  assert.match(js, /chart\.setData\(targetRange\(context, args\), chartSeriesByFrom\(args\.series_by\)\)/);
  assert.match(js, /chart\.setPosition\(requiredString\(args, 'start_cell', 'excel\.update_chart position requires start_cell\.'\), optionalName\(args\.end_cell\)\)/);
  assert.match(js, /chart\.width = Number\(args\.width\)/);
  assert.match(js, /chart\.height = Number\(args\.height\)/);
  assert.match(js, /const image = chart\.getImage\(optionalNumber\(args\.width\), optionalNumber\(args\.height\), chartImageFittingModeFrom\(args\.fitting_mode\)\)/);
  assert.match(js, /chart\.delete\(\)/);
  assert.match(js, /function targetChart\(context, args\)/);
  assert.match(js, /function chartMetadata\(chart\)/);
  assert.match(js, /function chartLegendPositionFrom\(value\)/);
  assert.match(js, /function chartAxisTypeFrom\(value\)/);
  assert.match(js, /function chartAxisGroupFrom\(value\)/);
  assert.match(js, /function chartSeriesByFrom\(value\)/);
  assert.match(js, /function chartImageFittingModeFrom\(value\)/);
  assert.match(js, /function optionalNumber\(value\)/);
  assert.match(js, /requireRequirementSet\('ExcelApi', '1\.8', 'pivot table creation'\)/);
  assert.match(js, /requireRequirementSet\('ExcelApi', '1\.8', 'pivot table hierarchy updates'\)/);
  assert.match(js, /requireRequirementSet\('ExcelApi', '1\.12', 'pivot table filters'\)/);
  assert.match(js, /context\.workbook\.pivotTables\.add\(requiredString\(args, 'name', 'excel\.create_pivot_table requires name\.'\), pivotSource\(context, args\), requiredString\(args, 'destination', 'excel\.create_pivot_table requires destination\.'\)\)/);
  assert.match(js, /const pivot = targetPivotTable\(context, args\)/);
  assert.match(js, /pivot\.refresh\(\)/);
  assert.match(js, /pivot\.delete\(\)/);
  assert.match(js, /pivot\.rowHierarchies\.add\(pivot\.hierarchies\.getItem\(hierarchy\)\)/);
  assert.match(js, /pivot\.columnHierarchies\.add\(pivot\.hierarchies\.getItem\(hierarchy\)\)/);
  assert.match(js, /pivot\.filterHierarchies\.add\(pivot\.hierarchies\.getItem\(hierarchy\)\)/);
  assert.match(js, /const dataHierarchy = pivot\.dataHierarchies\.add\(pivot\.hierarchies\.getItem\(hierarchy\)\)/);
  assert.match(js, /dataHierarchy\.summarizeBy = aggregationFunctionFrom\(args\.summarize_by\)/);
  assert.match(js, /pivot\.layout\.layoutType = pivotLayoutTypeFrom\(args\.layout_type\)/);
  assert.match(js, /pivotField\(pivot, args\)\.applyFilter\(pivotFiltersFrom\(args\)\)/);
  assert.match(js, /function targetPivotTable\(context, args\)/);
  assert.match(js, /function pivotSource\(context, args\)/);
  assert.match(js, /function pivotTableMetadata\(pivot, range\)/);
  assert.match(js, /function updatePivotHierarchy\(pivot, args\)/);
  assert.match(js, /function aggregationFunctionFrom\(value\)/);
  assert.match(js, /function pivotLayoutTypeFrom\(value\)/);
  assert.match(js, /function pivotFiltersFrom\(args\)/);
  assert.match(js, /function pivotField\(pivot, args\)/);
  assert.match(js, /targetSortObject\(context, args\)/);
  assert.match(js, /sort\.apply\(sortFieldsFrom\(args\.fields\), Boolean\(args\.match_case\), args\.has_headers !== false/);
  assert.match(js, /table\.sort\.apply\(sortFieldsFrom\(args\.fields\), Boolean\(args\.match_case\), sortMethodFrom\(args\.method\)\)/);
  assert.match(js, /targetWorksheet\(context, args\)\.autoFilter/);
  assert.match(js, /autoFilter\.apply\(range, Number\(args\.column_index\), filterCriteriaFrom\(args\.criteria\)\)/);
  assert.match(js, /table\.columns\.getItem\(requiredString\(args, 'column', 'excel\.apply_filter requires column for table filters\.'\)\)\.filter\.apply\(filterCriteriaFrom\(args\.criteria\)\)/);
  assert.match(js, /excel\.read_range/);
  assert.match(js, /excel\.write_range/);
  assert.match(js, /excel\.add_sheet/);
  assert.match(js, /excel\.set_formula/);
  assert.match(js, /excel\.format_range/);
  assert.match(js, /excel\.create_table/);
  assert.match(js, /excel\.create_chart/);
  assert.match(js, /async function readRange/);
  assert.match(js, /async function writeRange/);
  assert.match(js, /async function addSheet/);
  assert.match(js, /async function setFormula/);
  assert.match(js, /async function formatRange/);
  assert.match(js, /async function createTable/);
  assert.match(js, /async function createChart/);
  assert.match(js, /worksheet\.getRange\(address\)/);
  assert.match(js, /range\.values = args\.values/);
  assert.match(js, /context\.workbook\.worksheets\.add/);
  assert.match(js, /range\.formulas = formulaMatrixFrom\(args, range\.rowCount, range\.columnCount\)/);
  assert.match(js, /range\.format\.font\.bold/);
  assert.match(js, /range\.format\.horizontalAlignment = alignmentFrom\(args\.horizontal_alignment, 'horizontal'/);
  assert.match(js, /range\.format\.verticalAlignment = alignmentFrom\(args\.vertical_alignment, 'vertical'/);
  assert.match(js, /range\.format\.wrapText = Boolean\(args\.wrap_text\)/);
  assert.match(js, /applyBorders\(range, args\.borders\)/);
  assert.match(js, /range\.format\.autofitColumns\(\)/);
  assert.match(js, /range\.format\.autofitRows\(\)/);
  assert.match(js, /requireRequirementSet\('ExcelApi', '1\.2', 'autofit formatting'\)/);
  assert.match(js, /range\.numberFormat = matrixFromScalar/);
  assert.match(js, /range\.numberFormat = numberFormatMatrixFrom/);
  assert.match(js, /function formulaMatrixFrom\(args, rows, columns\)/);
  assert.match(js, /function numberFormatMatrixFrom\(args, rows, columns\)/);
  assert.match(js, /validateMatrixShape\(args\.formulas, rows, columns, 'formulas'\)/);
  assert.match(js, /validateMatrixShape\(args\.number_formats, rows, columns, 'number_formats'\)/);
  assert.match(js, /function validateMatrixShape\(matrix, rows, columns, label\)/);
  assert.match(js, /officeMcpCode: 'HOST_CAPABILITY_UNAVAILABLE'/);
  assert.match(js, /function alignmentFrom\(value, axis\)/);
  assert.match(js, /function applyBorders\(range, borders\)/);
  assert.match(js, /range\.format\.borders\.getItem\(borderIndexFrom\(border\.side\)\)/);
  assert.match(js, /rangeBorder\.style = borderLineStyleFrom\(border\.style\)/);
  assert.match(js, /rangeBorder\.weight = borderWeightFrom\(border\.weight\)/);
  assert.match(js, /function borderIndexFrom\(value\)/);
  assert.match(js, /function borderLineStyleFrom\(value\)/);
  assert.match(js, /function borderWeightFrom\(value\)/);
  assert.match(js, /function sortFieldsFrom\(fields\)/);
  assert.match(js, /function filterCriteriaFrom\(criteria\)/);
  assert.match(js, /function filterOnFrom\(value\)/);
  assert.match(js, /function sortOrientationFrom\(value\)/);
  assert.match(js, /context\.workbook\.tables\.add/);
  assert.match(js, /worksheet\.charts\.add/);
  assert.match(js, /function chartTypeFrom/);
  assert.match(js, /function requiredString/);
  assert.match(js, /INVALID_ARGUMENT/);
  assert.match(js, /Excel\.run/);
  assert.match(js, /OfficeCtlCommon/);
  assert.match(js, /OfficeCtlAddinChannel/);
  assert.match(js, /OfficeCtlLogger/);
  assert.match(js, /OfficeCtlTaskHistory/);
  assert.match(js, /window\.__OFFICE_MCP_TASKPANE_READY__ = true/);
  assert.match(js, /function whenOfficeReady\(callback\)/);
  assert.match(js, /!window\.Office \|\| typeof Office\.onReady !== 'function'/);
  assert.doesNotMatch(js, /const \{ completed \} = taskStore\.snapshot\(\)/);
  assert.doesNotMatch(js, /console\.(log|warn|error)/);
  assert.doesNotMatch(js, /method: 'register'/);
  assert.doesNotMatch(js, /method: 'session\.added'/);
});


test('Excel task pane keeps settings inline and compact at narrow widths', () => {
  const html = readFileSync(join(ADDIN_ROOT, 'public', 'taskpane.html'), 'utf8');
  const css = readFileSync(join(ADDIN_ROOT, '..', 'common', 'taskpane.css'), 'utf8');

  assert.match(css, /body \{[\s\S]*min-width: 320px;[\s\S]*overflow-x: hidden;/);
  assert.match(css, /\.taskpane-shell \{[\s\S]*align-content: start;[\s\S]*gap: 10px;[\s\S]*padding: 10px;/);
  assert.match(css, /\.summary-panel \{[\s\S]*display: grid;[\s\S]*gap: 10px;/);
  assert.match(css, /\.empty-state \{[\s\S]*padding: 10px;/);
  assert.match(css, /#documentTitle \{[\s\S]*display: -webkit-box;[\s\S]*-webkit-line-clamp: 2;/);
  assert.doesNotMatch(css, /\b(min-)?height:\s*(1[2-9]\d|[2-9]\d{2,})px/);
  assert.doesNotMatch(cssRule(css, '.summary-panel'), /\bheight:/);
  assert.doesNotMatch(cssRule(css, '.current-task-panel'), /\bheight:/);
  assert.doesNotMatch(cssRule(css, '.history-panel'), /\bheight:/);
  assert.doesNotMatch(css, /overflow-x:\s*(auto|scroll)/);

  const summaryStart = html.indexOf('class="panel summary-panel"');
  const daemonFormIndex = html.indexOf('class="daemon-endpoint-form"');
  const currentTaskIndex = html.indexOf('id="currentTaskHeading"');
  assert.ok(summaryStart !== -1 && daemonFormIndex !== -1, 'summary and daemon form exist');
  assert.ok(daemonFormIndex > summaryStart, 'daemon settings are inline in document metadata');
  assert.ok(daemonFormIndex < currentTaskIndex, 'daemon settings appear before current task');
  assert.doesNotMatch(html, /<section id="settingsPanel"/);
});
test('Excel task pane announces session only after successful register response', () => {
  const js = readFileSync(join(ADDIN_ROOT, 'public', 'taskpane.js'), 'utf8');
  const registerBody = functionBody(js, 'register');
  const responseBody = functionBody(js, 'handleRegisterResponse');

  assert.doesNotMatch(registerBody, /announceSession\(/);
  assert.match(responseBody, /serverInfo = registerResult\(message, PROTOCOL_VERSION\)/);
  assert.match(responseBody, /enableAutoOpen\(\)\.then\(\(\) => announceSession\(\)\)\.catch/);
  assert.match(responseBody, /session\.announce\.failed/);
});

function functionBody(source, name) {
  const start = source.indexOf(`function ${name}(`);
  assert.notEqual(start, -1, `missing function ${name}`);
  const open = source.indexOf('{', start);
  let depth = 0;
  for (let index = open; index < source.length; index += 1) {
    if (source[index] === '{') depth += 1;
    if (source[index] === '}') depth -= 1;
    if (depth === 0) return source.slice(open + 1, index);
  }
  assert.fail(`unterminated function ${name}`);
}

function cssRule(source, selector) {
  const escaped = selector.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const match = source.match(new RegExp(`${escaped}\\s*\\{([\\s\\S]*?)\\}`));
  return match?.[1] || '';
}
