import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import test from 'node:test';

const ADDIN_ROOT = process.cwd();

test('Excel add-in manifest targets workbook host and versioned task pane', () => {
  const manifest = readFileSync(join(ADDIN_ROOT, 'manifest.xml'), 'utf8');
  const html = readFileSync(join(ADDIN_ROOT, 'public', 'taskpane.html'), 'utf8');
  const js = readFileSync(join(ADDIN_ROOT, 'public', 'taskpane.js'), 'utf8');

  assert.match(manifest, /<Host Name="Workbook" \/>/);
  assert.match(manifest, /<Set Name="ExcelApi" MinVersion="1\.1" \/>/);
  assert.match(manifest, /<Version>1\.0\.0\.12<\/Version>/);
  assert.match(manifest, /excel\/taskpane\.html\?v=0\.1\.12/);
  assert.match(html, /common\/taskpane\.css\?v=0\.1\.12/);
  assert.match(html, /common\/addin-channel\.js\?v=0\.1\.12/);
  assert.match(html, /excel\/taskpane\.js\?v=0\.1\.12/);
  assert.match(html, /<script src="https:\/\/appsforoffice\.microsoft\.com\/lib\/1\/hosted\/office\.js"><\/script>/);
  assert.doesNotMatch(html, /<script async src="https:\/\/appsforoffice\.microsoft\.com\/lib\/1\/hosted\/office\.js"><\/script>/);
  assert.match(js, /ADDIN_VERSION = '0\.1\.12'/);
});

test('Excel add-in uses product identity metadata and generated icon URLs', () => {
  const manifest = readFileSync(join(ADDIN_ROOT, 'manifest.xml'), 'utf8');
  const html = readFileSync(join(ADDIN_ROOT, 'public', 'taskpane.html'), 'utf8');

  assert.match(manifest, /<ProviderName>Office MCP Control<\/ProviderName>/);
  assert.match(manifest, /<DisplayName DefaultValue="Office MCP Control" \/>/);
  assert.match(manifest, /Control live Excel workbooks through a local productivity automation control utility\./);
  assert.match(manifest, /<bt:String id="OfficeMcp\.GroupLabel" DefaultValue="Office MCP Control" \/>/);
  assert.match(manifest, /<bt:String id="OfficeMcp\.OpenPane\.Label" DefaultValue="Open Control Panel" \/>/);
  assert.match(manifest, /Office MCP Control for this workbook/);
  assert.match(manifest, /https:\/\/localhost:8765\/assets\/icon-32\.png/);
  assert.match(manifest, /https:\/\/localhost:8765\/assets\/icon-80\.png/);
  assert.doesNotMatch(manifest, /DefaultValue="office-mcp(?: for Excel)?"/);
  assert.doesNotMatch(manifest, /DefaultValue="Open"/);
  assert.match(html, /<title>MCP Control<\/title>/);
  assert.match(html, /<img class="product-mark" src="\/assets\/icon-32\.png" width="32" height="32" alt="" aria-hidden="true" \/>/);
  assert.match(html, /<h1>MCP Control<\/h1>/);
});

test('Excel task pane uses common channel and registers Excel runtime metadata', () => {
  const html = readFileSync(join(ADDIN_ROOT, 'public', 'taskpane.html'), 'utf8');
  const css = readFileSync(join(ADDIN_ROOT, '..', 'common', 'taskpane.css'), 'utf8');
  const js = readFileSync(join(ADDIN_ROOT, 'public', 'taskpane.js'), 'utf8');

  assert.match(html, /id="connectionBadge"/);
  assert.match(html, /id="runtimeVersions"/);
  assert.match(html, /id="serverVersion"/);
  assert.match(html, /id="protocolVersion"/);
  assert.match(html, /<dd id="runtimeVersions"><span id="serverVersion">Server Unknown<\/span> \/ <span id="protocolVersion">Protocol 1\.0<\/span><\/dd>/);
  assert.match(html, /id="hostPlatform"/);
  assert.match(html, /<dd id="protection">Not protected<\/dd>/);
  assert.match(html, /<dd id="documentState">Editable<\/dd>/);
  assert.match(html, /class="metadata-copy" data-copy-target="session" aria-label="Copy session ID" title="Copy session ID"/);
  assert.match(html, /class="daemon-endpoint-input" name="daemonEndpoint" type="url" inputmode="url" autocomplete="off" spellcheck="false" aria-label="Daemon endpoint"/);
  assert.doesNotMatch(html, /id="endpointError"/);
  assert.doesNotMatch(html, /class="field-error"/);
  assert.match(html, /id="historyList"/);
  assert.match(html, /class="panel summary-panel"/);
  assert.match(html, /class="summary-layout"/);
  assert.match(html, /class="metadata-section document-metadata"/);
  assert.match(html, /class="metadata-section daemon-metadata"/);
  assert.match(html, /<h2 id="daemonHeading">Daemon<\/h2>/);
  assert.match(html, /class="tools-panel"/);
  assert.match(html, /<span>Tools<\/span>/);
  assert.match(html, /id="toolList"/);
  assert.match(html, /0\/0/);
  assert.doesNotMatch(html, /Enabled \d+ of \d+/);
  assert.match(html, /id="toolModeControl" class="tool-mode-control" role="radiogroup" aria-label="Tool capability mode"/);
  assert.match(html, /data-tool-mode="read"/);
  assert.match(html, /data-tool-mode="write"/);
  assert.match(html, /data-tool-mode="all"/);
  assert.doesNotMatch(html, /Tool Permissions/);
  assert.doesNotMatch(html, /id="toolPermissionList"/);
  assert.doesNotMatch(html, /id="enabledToolCount"/);
  assert.match(html, /class="daemon-endpoint-input" name="daemonEndpoint" type="url" inputmode="url" autocomplete="off" spellcheck="false" aria-label="Daemon endpoint"/);
  assert.match(html, /id="saveEndpoint" class="icon-button reconnect-button" type="submit" aria-label="Reconnect daemon" title="Reconnect daemon"/);
  assert.doesNotMatch(html, /id="settingsToggle"/);
  assert.doesNotMatch(html, /id="settingsPanel"/);
  assert.doesNotMatch(html, /Save Endpoint/);
  assert.ok(html.indexOf('class="daemon-endpoint-form"') < html.indexOf('id="runtimeVersions"'));
  assert.match(html, /Connecting…/);
  assert.match(html, /placeholder="wss:\/\/localhost:8765\/addin"/);
  assert.doesNotMatch(html, /Connecting\.\.\./);
  assert.doesNotMatch(html, /addin\.\.\./);
  assert.match(readFileSync(join(ADDIN_ROOT, '..', 'common', 'taskpane.css'), 'utf8'), /--accent: #3b6478/);
  assert.match(readFileSync(join(ADDIN_ROOT, 'public', 'taskpane.css'), 'utf8'), /--accent: #217346/);
  assert.match(css, /\.summary-panel/);
  assert.doesNotMatch(css, /\.field-error/);
  assert.match(css, /\.identity \{[\s\S]*grid-template-columns: 32px minmax\(0, 1fr\);/);
  assert.match(css, /\.product-mark \{[\s\S]*width: 32px;[\s\S]*height: 32px;/);
  assert.match(css, /\.control-glyph \{[\s\S]*width: 18px;[\s\S]*stroke: currentColor;/);
  assert.match(css, /\.tool-list/);
  assert.match(css, /\.daemon-endpoint-form/);
  assert.match(css, /\.reconnect-button/);
  assert.match(css, /\.tool-permission-row/);
  assert.match(css, /\.tool-toggle,\r?\n\.group-toggle/);
  assert.doesNotMatch(css, /is-editing-tools/);
  assert.match(css, /\.metadata-copy \{[\s\S]*display: inline-flex;[\s\S]*min-height: 32px;[\s\S]*text-align: left;/);
  assert.match(css, /\.metadata-copy code \{[\s\S]*overflow-wrap: anywhere;[\s\S]*white-space: normal;/);
  assert.match(css, /\.task-command-id \{[\s\S]*display: flex;[\s\S]*gap: 4px;/);
  assert.match(css, /\.inline-copy \{[\s\S]*display: inline-flex;[\s\S]*min-height: 32px;[\s\S]*background: transparent;[\s\S]*cursor: pointer;/);
  assert.match(css, /\.metadata-copy:hover,[\s\S]*\.inline-copy:focus-visible \{[\s\S]*background: var\(--surface-raised\);/);
  assert.match(css, /prefers-reduced-motion/);
  assert.match(css, /forced-colors: active/);
  assert.match(js, /const TOOL_GROUPS = \[/);
  assert.match(js, /\{ label: 'Workbook', tools: \['excel\.get_workbook_info', 'excel\.save', 'excel\.calculate', 'excel\.list_named_items', 'excel\.update_named_item', 'excel\.get_document_properties', 'excel\.update_document_properties'\] \}/);
  assert.match(js, /\{ label: 'Data', tools: \['excel\.sort_range', 'excel\.apply_filter'\] \}/);
  assert.match(js, /\{ label: 'Table', tools: \['excel\.create_table', 'excel\.update_table'\] \}/);
  assert.match(js, /\{ label: 'Chart', tools: \['excel\.create_chart', 'excel\.update_chart'\] \}/);
  assert.match(js, /\{ label: 'PivotTable', tools: \['excel\.create_pivot_table', 'excel\.update_pivot_table'\] \}/);
  assert.match(js, /\{ label: 'Shapes', tools: \['excel\.insert_image', 'excel\.list_shapes', 'excel\.update_shape'\] \}/);
  assert.match(js, /\{ label: 'Review', tools: \['excel\.add_comment', 'excel\.list_comments', 'excel\.update_comment'\] \}/);
  assert.match(js, /const TOOL_METADATA = new Map\(\[/);
  assert.match(js, /\['excel\.save', \{ category: 'Workbook', sideEffect: 'mutating'/);
  assert.match(js, /\['excel\.calculate', \{ category: 'Workbook', sideEffect: 'mutating'/);
  assert.match(js, /\['excel\.list_named_items', \{ category: 'Workbook', sideEffect: 'read'/);
  assert.match(js, /\['excel\.update_named_item', \{ category: 'Workbook', sideEffect: 'destructive'/);
  assert.match(js, /\['excel\.get_document_properties', \{ category: 'Workbook', sideEffect: 'read', description: 'Read workbook metadata and custom properties\.' \}\]/);
  assert.match(js, /\['excel\.update_document_properties', \{ category: 'Workbook', sideEffect: 'mutating', description: 'Update workbook metadata and custom properties\.' \}\]/);
  assert.match(js, /\['excel\.sort_range', \{ category: 'Data', sideEffect: 'mutating'/);
  assert.match(js, /\['excel\.apply_filter', \{ category: 'Data', sideEffect: 'mutating'/);
  assert.match(js, /\['excel\.update_table', \{ category: 'Table', sideEffect: 'destructive'/);
  assert.match(js, /\['excel\.update_chart', \{ category: 'Chart', sideEffect: 'destructive'/);
  assert.match(js, /\['excel\.create_pivot_table', \{ category: 'PivotTable', sideEffect: 'mutating'/);
  assert.match(js, /\['excel\.update_pivot_table', \{ category: 'PivotTable', sideEffect: 'destructive'/);
  assert.match(js, /\['excel\.insert_image', \{ category: 'Shapes', sideEffect: 'mutating'/);
  assert.match(js, /\['excel\.list_shapes', \{ category: 'Shapes', sideEffect: 'read'/);
  assert.match(js, /\['excel\.update_shape', \{ category: 'Shapes', sideEffect: 'destructive'/);
  assert.match(js, /\['excel\.add_comment', \{ category: 'Review', sideEffect: 'mutating'/);
  assert.match(js, /\['excel\.list_comments', \{ category: 'Review', sideEffect: 'read'/);
  assert.match(js, /\['excel\.update_comment', \{ category: 'Review', sideEffect: 'destructive'/);
  assert.match(js, /TOOL_PERMISSION_STORAGE_KEY/);
  assert.match(js, /TOOL_PERMISSION_MODE_STORAGE_KEY/);
  assert.match(js, /const toolListEl = document\.getElementById\('toolList'\)/);
  assert.match(js, /const toolModeControlEl = document\.getElementById\('toolModeControl'\)/);
  assert.match(js, /function renderToolSummary\(\)/);
  assert.match(js, /toolCountEl\.textContent = `\$\{effective\.length\}\/\$\{AVAILABLE_TOOLS\.length\}`/);
  assert.match(functionBody(js, 'renderToolSummary'), /const supportedInGroup = tools\.filter\(\(tool\) => isToolSupported\(tool\)\)/);
  assert.match(functionBody(js, 'renderToolSummary'), /\$\{supportedInGroup\.length === 0 \? 'disabled' : ''\}/);
  assert.match(js, /\$\{enabledInGroup\.length\}\/\$\{tools\.length\}/);
  assert.doesNotMatch(js, /Enabled \$\{/);
  assert.match(js, /function isToolAllowedByMode\(tool\)/);
  assert.match(js, /isToolAllowedByCapabilityMode,/);
  assert.match(functionBody(js, 'isToolAllowedByMode'), /return isToolAllowedByCapabilityMode\(toolPermissionMode, sideEffect\);/);
  assert.match(js, /function handleToolModeChange\(event\)/);
  assert.match(js, /function handleToolGroupPermissionChange\(event\)/);
  assert.match(functionBody(js, 'handleToolGroupPermissionChange'), /toolPermissionMode = leastPermissiveModeForTools\(group\.tools, toolPermissionMode\)/);
  assert.match(js, /function leastPermissiveModeForTools\(tools, currentMode\)/);
  assert.match(functionBody(js, 'leastPermissiveModeForTools'), /return 'write';/);
  assert.match(functionBody(js, 'leastPermissiveModeForTools'), /return 'all';/);
  assert.match(functionBody(js, 'leastPermissiveModeForTools'), /isToolAllowedByCapabilityMode\(currentMode, sideEffect\)/);
  assert.match(js, /renderSharedToolModeControl\(toolModeControlEl, toolPermissionMode\)/);
  assert.doesNotMatch(functionBody(js, 'renderToolModeControl'), /querySelectorAll\('\[data-tool-mode\]'\)/);
  assert.match(js, /renderToolSummary\(\)/);
  assert.match(js, /function toolControlMarkup\(tool\)/);
  assert.doesNotMatch(js, /function renderToolPermissions\(\)/);
  assert.doesNotMatch(js, /toolPermissionListEl/);
  assert.match(js, /function effectiveTools\(\)/);
  assert.match(js, /return AVAILABLE_TOOLS\.filter\(\(tool\) => isToolSupported\(tool\) && isToolEnabled\(tool\) && isToolAllowedByMode\(tool\)\)/);
  assert.match(js, /available_tools: effectiveTools\(\)/);
  assert.match(js, /sessionUpdatedNotification\(\{/);
  assert.match(js, /patch: \{ available_tools: effectiveTools\(\) \}/);
  assert.match(js, /TOOL_DISABLED_BY_USER/);
  assert.match(js, /function isExcelHost\(info\)/);
  assert.match(js, /Office\.HostType\?\.Excel/);
  assert.match(js, /Office\.context\?\.diagnostics\?\.host/);
  assert.match(js, /window\.Excel\?\.run/);
  assert.match(js, /isSetSupported\?\.\('ExcelApi', '1\.1'\)/);
  assert.match(js, /app: 'excel'/);
  assert.match(js, /clearEndpointOverride/);
  assert.match(js, /currentOriginEndpoint/);
  assert.match(js, /function tryCurrentOriginEndpointFallback\(failedEndpoint\)/);
  assert.match(js, /new TaskHistoryStore\(\{ redactText \}\)/);
  assert.match(js, /const \{ history, historyLimit \} = taskStore\.snapshot\(\)/);
  assert.match(js, /historyCountEl\.textContent = `\$\{history\.length\} \/ \$\{historyLimit\}`/);
  assert.match(js, /function taskMarkup\(task\)/);
  assert.match(js, /requestId: currentTask\.requestId/);
  assert.match(js, /const commandId = commandIdMarkup\(task\.requestId, \{ escapeHtml \}\)/);
  assert.match(js, /const requestId = message\.params\?\.request_id \|\| String\(message\.id\)/);
  assert.match(js, /taskStore\.start\(requestId, tool, message\.params \|\| \{\}, message\.params\?\.timeout_ms\)/);
  assert.match(js, /taskStore\.isCancelled\(requestId\)/);
  assert.match(js, /taskStore\.consumeCancellation\(requestId\)/);
  assert.match(js, /function cancelledError\(tool\)/);
  assert.match(js, /const \{ boolLabel, escapeHtml, fileName, formatDuration, formatTime, titleCase, redactText \} = window\.OfficeCtlCommon/);
  assert.match(js, /const metadata = taskMetadataMarkup\(task, \{ escapeHtml, formatTime, redactText, valueLabel: boolLabel \}\)/);
  assert.match(js, /taskStatusClass/);
  assert.match(js, /taskStatusLabel/);
  assert.match(js, /const tone = taskStatusClass\(task\.status \|\| 'running'\)/);
  assert.match(js, /<span class="status-badge \$\{tone\}">\$\{escapeHtml\(taskStatusLabel\(task\.status \|\| 'running'\)\)\}<\/span>/);
  assert.doesNotMatch(functionBody(js, 'taskMarkup'), /titleCase\(task\.status\)/);
  assert.doesNotMatch(js, /function valueLabel\(value\)/);
  assert.match(js, /mapped\.office_mcp_code === 'CANCELLED' \? 'cancelled' : 'failure'/);
  assert.doesNotMatch(js, /Discard unsaved endpoint changes\?/);
  assert.match(js, /Connecting…/);
  assert.match(js, /Reconnecting…/);
  assert.match(js, /Registering…/);
  assert.doesNotMatch(js, /Connecting\.\.\./);
  assert.doesNotMatch(js, /Reconnecting\.\.\./);
  assert.doesNotMatch(js, /Registering\.\.\./);
  assert.doesNotMatch(js, /settingsToggleEl/);
  assert.match(js, /document\.addEventListener\('click', handleMetadataCopy\)/);
  assert.match(js, /setConnectionState: setSharedConnectionState/);
  assert.match(js, /setSharedConnectionState\(\{ badge: connectionBadgeEl, detail: connectionDetailEl, announcer: announcerEl \}, state, label\)/);
  assert.match(js, /function setStatus\(text\) \{\s*connectionDetailEl\.textContent = text;\s*setConnectionState\('failed', text\);\s*\}/);
  assert.doesNotMatch(js, /function setStatus\(text\) \{\s*connectionBadgeEl\.textContent = text;\s*connectionDetailEl\.textContent = text;\s*\}/);
  assert.match(js, /async function handleMetadataCopy\(event\)/);
  assert.match(js, /copyMetadataValue\(event, \{ document, navigator, announcer: announcerEl, logger \}\)/);
  assert.doesNotMatch(js, /event\.target\.closest\('\[data-copy-target\], \[data-copy-value\]'\)/);
  assert.match(js, /setCopyableMetadata/);
  assert.match(js, /const \{[\s\S]*renderRuntimeVersions[\s\S]*\} = window\.OfficeCtlMainUi/);
  assert.match(readFileSync(join(ADDIN_ROOT, '..', 'common', 'main-ui.js'), 'utf8'), /function setCopyableMetadata\(element, value\)/);
  assert.match(js, /middleTruncate/);
  assert.match(readFileSync(join(ADDIN_ROOT, '..', 'common', 'main-ui.js'), 'utf8'), /function middleTruncate\(value, maxLength = 30\)/);
  assert.match(readFileSync(join(ADDIN_ROOT, '..', 'common', 'main-ui.js'), 'utf8'), /return `\$\{text\.slice\(0, head\)\}\$\{marker\}\$\{text\.slice\(text\.length - tail\)\}`/);
  assert.doesNotMatch(js, /function fallbackCopy\(value\)/);
  assert.doesNotMatch(js, /is-editing-tools/);
  assert.doesNotMatch(js, /function activateSettingsWithKeyboard/);
  assert.match(js, /saveEndpointEl\.disabled = true/);
  assert.match(js, /saveEndpointEl\.setAttribute\('aria-busy', 'true'\)/);
  assert.match(js, /renderStaticMetadata\(\{ session: sessionEl, daemon: daemonEl, serverVersion: serverVersionEl, protocolVersion: protocolVersionEl, hostPlatform: hostPlatformEl \}, \{ sessionId, endpoint: configuredEndpoint\(\), serverInfo, protocolVersion: PROTOCOL_VERSION, defaultHost: 'Excel' \}\)/);
  assert.doesNotMatch(functionBody(js, 'renderStaticState'), /setCopyableMetadata\(sessionEl/);
  assert.doesNotMatch(functionBody(js, 'renderStaticState'), /renderRuntimeVersions\(/);
  assert.doesNotMatch(functionBody(js, 'renderStaticState'), /officeHostSummary\(/);
  assert.match(js, /protectionLabel,/);
  assert.match(js, /documentStateLabel,/);
  assert.doesNotMatch(js, /function protectionLabel\(info\)/);
  assert.doesNotMatch(js, /function documentStateLabel\(info\)/);
  assert.doesNotMatch(js, /protectionEl\.textContent = workbook\.protection\?\.kind \|\| 'Unknown'/);
  assert.match(readFileSync(join(ADDIN_ROOT, '..', 'common', 'main-ui.js'), 'utf8'), /function protectionLabel\(info = \{\}\)/);
  assert.match(readFileSync(join(ADDIN_ROOT, '..', 'common', 'main-ui.js'), 'utf8'), /function documentStateLabel\(info = \{\}\)/);
  assert.doesNotMatch(js, /Dirty: \$\{valueLabel/);
  assert.match(js, /registerRequest\(requestId/);
  assert.match(js, /Office\.AutoShowTaskpaneWithDocument/);
  assert.match(js, /function enableAutoOpen\(\)/);
  assert.match(js, /sessionAddedNotification\(\{/);
  assert.match(js, /excel\.get_workbook_info/);
  assert.match(js, /excel\.save/);
  assert.match(js, /excel\.calculate/);
  assert.match(js, /excel\.list_named_items/);
  assert.match(js, /excel\.update_named_item/);
  assert.match(js, /excel\.list_sheets/);
  assert.match(js, /excel\.update_sheet/);
  assert.match(js, /excel\.delete_sheet/);
  assert.doesNotMatch(js, /'excel\.get_used_range'/);
  assert.match(js, /excel\.insert_range/);
  assert.match(js, /excel\.clear_range/);
  assert.match(js, /excel\.set_hyperlink/);
  assert.match(js, /excel\.set_data_validation/);
  assert.match(js, /excel\.copy_range/);
  assert.match(js, /excel\.find_replace_cells/);
  assert.match(js, /excel\.list_conditional_formats/);
  assert.match(js, /excel\.update_conditional_format/);
  assert.match(js, /excel\.sort_range/);
  assert.match(js, /excel\.apply_filter/);
  assert.match(js, /excel\.update_table/);
  assert.match(js, /excel\.update_chart/);
  assert.match(js, /excel\.create_pivot_table/);
  assert.match(js, /excel\.update_pivot_table/);
  assert.match(js, /excel\.insert_image/);
  assert.match(js, /excel\.list_shapes/);
  assert.match(js, /excel\.update_shape/);
  assert.match(js, /excel\.add_comment/);
  assert.match(js, /excel\.list_comments/);
  assert.match(js, /excel\.update_comment/);
  assert.match(js, /case 'excel.get_workbook_info':/);
  assert.match(js, /case 'excel.save':/);
  assert.match(js, /case 'excel.calculate':/);
  assert.match(js, /case 'excel.list_named_items':/);
  assert.match(js, /case 'excel.update_named_item':/);
  assert.match(js, /case 'excel.get_document_properties':/);
  assert.match(js, /case 'excel.update_document_properties':/);
  assert.match(js, /case 'excel.list_sheets':/);
  assert.match(js, /case 'excel.update_sheet':/);
  assert.match(js, /case 'excel.delete_sheet':/);
  assert.doesNotMatch(js, /case 'excel.get_used_range':/);
  assert.match(js, /case 'excel.insert_range':/);
  assert.match(js, /case 'excel.clear_range':/);
  assert.match(js, /case 'excel.set_hyperlink':/);
  assert.match(js, /case 'excel.set_data_validation':/);
  assert.match(js, /case 'excel.copy_range':/);
  assert.match(js, /case 'excel.find_replace_cells':/);
  assert.match(js, /case 'excel.list_conditional_formats':/);
  assert.match(js, /case 'excel.update_conditional_format':/);
  assert.match(js, /case 'excel.sort_range':/);
  assert.match(js, /case 'excel.apply_filter':/);
  assert.match(js, /case 'excel.update_table':/);
  assert.match(js, /case 'excel.update_chart':/);
  assert.match(js, /case 'excel.create_pivot_table':/);
  assert.match(js, /case 'excel.update_pivot_table':/);
  assert.match(js, /case 'excel.insert_image':/);
  assert.match(js, /case 'excel.list_shapes':/);
  assert.match(js, /case 'excel.update_shape':/);
  assert.match(js, /case 'excel.add_comment':/);
  assert.match(js, /case 'excel.list_comments':/);
  assert.match(js, /case 'excel.update_comment':/);
  assert.match(js, /async function getWorkbookInfoTool/);
  assert.match(js, /async function saveWorkbook/);
  assert.match(js, /async function calculateWorkbook/);
  assert.match(js, /async function listNamedItems/);
  assert.match(js, /async function updateNamedItem/);
  const workbookInfoBody = functionBody(js, 'getWorkbookInfoTool');
  assert.match(workbookInfoBody, /worksheets\.load\('items\/id,items\/name,items\/position,items\/visibility,items\/tabColor'\)/);
  assert.match(workbookInfoBody, /requireRequirementSet\('ExcelApi', '1\.7', 'workbook styles'\)/);
  assert.match(workbookInfoBody, /context\.workbook\.styles/);
  assert.match(workbookInfoBody, /styles\.load\('items\/name'\)/);
  assert.match(workbookInfoBody, /styles: workbookStyleNames\(styles\)/);
  assert.match(js, /requireRequirementSet\('ExcelApi', '1\.11', 'workbook save'\)/);
  assert.match(js, /requireRequirementSet\('ExcelApi', '1\.2', 'full rebuild calculation'\)/);
  assert.match(js, /requireRequirementSet\('ExcelApi', '1\.4', 'sheet-scoped named items'\)/);
  assert.match(js, /requireRequirementSet\('ExcelApi', '1\.7', 'named item formula editing'\)/);
  assert.match(js, /context\.workbook\.names/);
  assert.match(js, /worksheet\.names/);
  assert.match(js, /namedItem\.getRangeOrNullObject\(\)/);
  assert.match(js, /existing\.delete\(\)/);
  assert.match(js, /context\.workbook\.save\(Excel\.SaveBehavior\.save\)/);
  assert.match(js, /application\.calculate\(calculationType\)/);
  assert.match(js, /function calculationTypeFrom\(value\)/);
  assert.match(js, /excel\.active_sheet_probe\.failed/);
  assert.match(js, /worksheets\.items\[0\]/);
  assert.match(js, /async function listSheets/);
  assert.match(js, /async function updateSheet/);
  assert.match(js, /async function deleteSheet/);
  assert.match(js, /worksheet\.freezePanes\.getLocationOrNullObject\(\)/);
  assert.match(js, /freezePanes\.freezeRows\(Number\(freeze\.rows\)\)/);
  assert.match(js, /freezePanes\.freezeColumns\(Number\(freeze\.columns\)\)/);
  assert.match(js, /freezePanes\.freezeAt\(worksheet\.getRange\(requiredNonEmptyString\(freeze\.at/);
  assert.match(js, /freezePanes\.unfreeze\(\)/);
  assert.match(js, /worksheet\.showGridlines = Boolean\(args\.show_gridlines\)/);
  assert.match(js, /worksheet\.showHeadings = Boolean\(args\.show_headings\)/);
  assert.match(js, /requireRequirementSet\('ExcelApi', '1\.7', 'worksheet freeze panes'\)/);
  assert.match(js, /requireRequirementSet\('ExcelApi', '1\.8', 'worksheet view flags'\)/);
  assert.match(js, /function validateSheetViewArgs\(args\)/);
  assert.match(js, /function sheetFrozenState\(freezeRange\)/);
  assert.doesNotMatch(js, /async function getUsedRange/);
  assert.match(js, /async function readRangeTarget/);
  assert.match(js, /async function insertRange/);
  assert.match(js, /async function clearRange/);
  assert.match(js, /async function setHyperlink/);
  assert.match(js, /async function setDataValidation/);
  assert.match(js, /async function copyRange/);
  assert.match(js, /async function findReplaceCells/);
  assert.match(js, /async function listConditionalFormats/);
  assert.match(js, /async function updateConditionalFormat/);
  assert.match(js, /async function sortRange/);
  assert.match(js, /async function applyFilter/);
  assert.match(js, /async function updateTable/);
  assert.match(js, /async function updateChart/);
  assert.match(js, /async function createPivotTable/);
  assert.match(js, /async function updatePivotTable/);
  assert.match(js, /async function insertImage/);
  assert.match(js, /async function listShapes/);
  assert.match(js, /async function updateShape/);
  assert.match(js, /requireRequirementSet\('ExcelApi', '1\.9', 'worksheet shapes'\)/);
  assert.match(js, /targetWorksheet\(context, args\)\.shapes/);
  assert.match(js, /shapes\.addImage\(requiredImageBase64\(args\)\)/);
  assert.match(js, /shape\.load\('id,name,type,left,top,width,height,altTextDescription,textFrame\/textRange\/text'\)/);
  assert.match(js, /function shapeMetadata\(shape\)/);
  assert.match(js, /text_preview: shape\.textFrame\?\.textRange\?\.text/);
  assert.match(js, /shape\.altTextDescription = String\(args\.alt_text/);
  assert.match(js, /shape\.textFrame\.textRange\.text = requiredString\(args, 'text', 'excel\.update_shape set_text requires text\.'\)/);
  assert.match(js, /shape\.setZOrder\(shapeZOrderFrom\(args\.z_order\)\)/);
  assert.match(js, /shape\.delete\(\)/);
  assert.match(js, /function requiredImageBase64\(args\)/);
  assert.match(js, /function shapeZOrderFrom\(value\)/);
  assert.match(js, /async function addComment/);
  assert.match(js, /async function listComments/);
  assert.match(js, /async function updateComment/);
  assert.match(js, /requireRequirementSet\('ExcelApi', '1\.10', 'threaded comments'\)/);
  assert.match(js, /requireRequirementSet\('ExcelApi', '1\.11', 'comment resolved state'\)/);
  assert.match(js, /context\.workbook\.comments/);
  assert.match(js, /worksheet\.comments/);
  assert.match(js, /const cell = requiredString\(args, 'cell', 'excel\.add_comment requires cell\.'\)/);
  assert.match(js, /worksheet\.comments\.add\(range, text\)/);
  assert.match(js, /comment\.replies\.add/);
  assert.match(js, /comment\.resolved = true/);
  assert.match(js, /comment\.resolved = false/);
  assert.match(js, /untrusted_source: true/);
  assert.match(js, /const insertShift = insertShiftDirectionFrom\(args\.shift\)/);
  assert.match(js, /validateInsertRangeShift\(args\.address, args\.shift\)/);
  assert.match(js, /const insertTarget = insertRangeAddress\(range, args\.shift, args\.count\)/);
  assert.match(js, /insertTarget\.insert\(insertShift\)/);
  assert.match(js, /function insertShiftDirectionFrom\(value\)/);
  assert.match(js, /function validateInsertRangeShift\(address, shift\)/);
  assert.match(js, /function insertRangeAddress\(range, shift, count\)/);
  assert.match(js, /const applyTo = clearApplyToFrom/);
  assert.match(js, /range\.clear\(applyTo\)/);
  assert.match(js, /range\.delete\(deleteShiftDirectionFrom\(deleteShift\)\)/);
  assert.match(js, /if \(args\.include_hyperlinks\) requireRequirementSet\('ExcelApi', '1\.7', 'range hyperlinks'\)/);
  assert.match(js, /if \(args\.include_validation\) requireRequirementSet\('ExcelApi', '1\.8', 'range data validation'\)/);
  assert.match(js, /range\.load\('hyperlink'\)/);
  assert.match(js, /range\.dataValidation\.load\('rule,ignoreBlanks,valid'\)/);
  assert.match(js, /hyperlinks: args\.include_hyperlinks \? hyperlinkMatrix\(range\) : undefined/);
  assert.match(js, /validation: args\.include_validation \? dataValidationSummary\(range\.dataValidation\) : undefined/);
  assert.match(js, /requireRequirementSet\('ExcelApi', '1\.7', 'range hyperlinks'\)/);
  assert.match(js, /validateHyperlinkArgs\(args\)/);
  assert.match(js, /range\.hyperlink = hyperlinkFromArgs\(args\)/);
  assert.match(js, /range\.clear\(Excel\.ClearApplyTo\.hyperlinks\)/);
  assert.match(js, /function validateHyperlinkArgs\(args\)/);
  assert.match(js, /function validateHyperlinkUrl\(url\)/);
  assert.match(js, /\['https:', 'http:', 'mailto:'\]/);
  assert.match(js, /function hyperlinkMatrix\(range\)/);
  assert.match(js, /requireRequirementSet\('ExcelApi', '1\.8', 'range data validation'\)/);
  assert.match(js, /validateDataValidationArgs\(args\)/);
  assert.match(js, /range\.dataValidation\.rule = dataValidationRuleFrom\(args\.rule\)/);
  assert.match(js, /range\.dataValidation\.clear\(\)/);
  assert.match(js, /function dataValidationRuleFrom\(rule\)/);
  assert.match(js, /function dataValidationSummary\(dataValidation\)/);
  assert.match(js, /function dataValidationOperatorFrom\(value\)/);
  assert.match(js, /untrusted_source: true/);
  assert.match(js, /const criteria = searchCriteriaFrom\(args\)/);
  assert.match(js, /range\.findOrNullObject\(query, criteria\)/);
  assert.match(js, /range\.replaceAll\(query, replacement, replaceCriteriaFrom/);
  assert.match(js, /requireRequirementSet\('ExcelApi', '1\.6', 'conditional formatting'\)/);
  assert.match(js, /targetConditionalFormatCollection\(context, args\)/);
  assert.match(js, /conditionalFormats\.load\('items\/id,items\/type,items\/priority,items\/stopIfTrue'\)/);
  assert.match(js, /conditionalFormats\.add\(conditionalFormatTypeFrom\(rule\.type\)\)/);
  assert.match(js, /conditionalFormats\.clearAll\(\)/);
  assert.match(js, /conditionalFormat\.delete\(\)/);
  assert.match(js, /applyConditionalFormatRule\(conditionalFormat, rule\)/);
  assert.match(js, /function validateConditionalFormatArgs\(args\)/);
  assert.match(js, /function conditionalFormatTypeFrom\(value\)/);
  assert.match(js, /function applyConditionalFormatRule\(conditionalFormat, rule\)/);
  assert.match(js, /function conditionalFormatSummary\(format\)/);
  assert.match(js, /requireRequirementSet\('ExcelApi', '1\.2', 'range sorting'\)/);
  assert.match(js, /requireRequirementSet\('ExcelApi', '1\.9', 'range filtering'\)/);
  assert.match(js, /requireRequirementSet\('ExcelApi', '1\.2', 'table filtering'\)/);
  assert.match(js, /requireRequirementSet\('ExcelApi', '1\.13', 'table resize'\)/);
  assert.match(js, /requireRequirementSet\('ExcelApi', '1\.3', 'table visual options'\)/);
  assert.match(js, /requireRequirementSet\('ExcelApi', '1\.7', 'chart axis selection'\)/);
  assert.match(js, /table\.rows\.add\(optionalIndex\(args\.index\), tableValuesFrom\(args\.values, 'rows'\), args\.always_insert !== false\)/);
  assert.match(js, /table\.columns\.add\(optionalIndex\(args\.index\), tableValuesFrom\(args\.values, 'columns'\), optionalName\(args\.name\)\)/);
  assert.match(js, /table\.resize\(requiredString\(args, 'address', 'excel\.update_table resize requires address\.'\)\)/);
  assert.match(js, /table\.name = requiredString\(args, 'name', 'excel\.update_table rename requires name\.'\)/);
  assert.match(js, /applyTableOptions\(table, args\)/);
  assert.match(js, /table\.delete\(\)/);
  assert.match(js, /function tableMetadata\(table, range, bodyRange, headerRange, totalRange\)/);
  assert.match(js, /const headerRange = table\.showHeaders \? table\.getHeaderRowRange\(\) : null/);
  assert.match(js, /const totalRange = table\.showTotals \? table\.getTotalRowRange\(\) : null/);
  assert.match(js, /if \(bodyRange\) bodyRange\.load\('address,rowCount,columnCount'\)/);
  assert.match(js, /if \(!range\) return \{ address: null, row_count: null, column_count: null \}/);
  assert.match(js, /function applyTableOptions\(table, args\)/);
  assert.match(js, /function tableValuesFrom\(values, label\)/);
  assert.match(js, /function optionalIndex\(value\)/);
  assert.match(js, /function optionalName\(value\)/);
  assert.match(js, /requireRequirementSet\('ExcelApi', '1\.2', 'chart image export'\)/);
  assert.match(js, /const chart = targetChart\(context, args\)/);
  assert.match(js, /chart\.title\.text = requiredString\(args, 'title', 'excel\.update_chart title requires title\.'\)/);
  assert.match(js, /chart\.legend\.position = chartLegendPositionFrom\(args\.position\)/);
  assert.match(js, /chart\.axes\.getItem\(chartAxisTypeFrom\(args\.axis\), chartAxisGroupFrom\(args\.axis_group\)\)/);
  assert.match(js, /chart\.setData\(await targetRange\(context, args\), chartSeriesByFrom\(args\.series_by\)\)/);
  assert.match(js, /chart\.setPosition\(requiredString\(args, 'start_cell', 'excel\.update_chart position requires start_cell\.'\), optionalName\(args\.end_cell\)\)/);
  assert.match(js, /chart\.width = Number\(args\.width\)/);
  assert.match(js, /chart\.height = Number\(args\.height\)/);
  assert.match(js, /const image = chart\.getImage\(optionalNumber\(args\.width\), optionalNumber\(args\.height\), chartImageFittingModeFrom\(args\.fitting_mode\)\)/);
  assert.match(js, /chart\.delete\(\)/);
  assert.match(js, /function targetChart\(context, args\)/);
  assert.match(js, /function chartMetadata\(chart\)/);
  assert.match(js, /function chartLegendPositionFrom\(value\)/);
  assert.match(js, /function chartAxisTypeFrom\(value\)/);
  assert.match(js, /function chartAxisGroupFrom\(value\)/);
  assert.match(js, /function chartSeriesByFrom\(value\)/);
  assert.match(js, /function chartImageFittingModeFrom\(value\)/);
  assert.match(js, /function optionalNumber\(value\)/);
  assert.match(js, /requireRequirementSet\('ExcelApi', '1\.8', 'pivot table creation'\)/);
  assert.match(js, /requireRequirementSet\('ExcelApi', '1\.8', 'pivot table hierarchy updates'\)/);
  assert.match(js, /requireRequirementSet\('ExcelApi', '1\.12', 'pivot table filters'\)/);
  assert.match(js, /context\.workbook\.pivotTables\.add\(requiredString\(args, 'name', 'excel\.create_pivot_table requires name\.'\), await pivotSource\(context, args\), requiredString\(args, 'destination', 'excel\.create_pivot_table requires destination\.'\)\)/);
  assert.match(js, /const pivot = targetPivotTable\(context, args\)/);
  assert.match(js, /pivot\.refresh\(\)/);
  assert.match(js, /pivot\.delete\(\)/);
  assert.match(js, /pivot\.rowHierarchies\.add\(pivot\.hierarchies\.getItem\(hierarchy\)\)/);
  assert.match(js, /pivot\.columnHierarchies\.add\(pivot\.hierarchies\.getItem\(hierarchy\)\)/);
  assert.match(js, /pivot\.filterHierarchies\.add\(pivot\.hierarchies\.getItem\(hierarchy\)\)/);
  assert.match(js, /const dataHierarchy = pivot\.dataHierarchies\.add\(pivot\.hierarchies\.getItem\(hierarchy\)\)/);
  assert.match(js, /dataHierarchy\.summarizeBy = aggregationFunctionFrom\(args\.summarize_by\)/);
  assert.match(js, /pivot\.layout\.layoutType = pivotLayoutTypeFrom\(args\.layout_type\)/);
  assert.match(js, /pivotField\(pivot, args\)\.applyFilter\(pivotFiltersFrom\(args\)\)/);
  assert.match(js, /function targetPivotTable\(context, args\)/);
  assert.match(js, /function pivotSource\(context, args\)/);
  assert.match(js, /function pivotTableMetadata\(pivot, range\)/);
  assert.match(js, /function updatePivotHierarchy\(pivot, args\)/);
  assert.match(js, /function aggregationFunctionFrom\(value\)/);
  assert.match(js, /function pivotLayoutTypeFrom\(value\)/);
  assert.match(js, /function pivotFiltersFrom\(args\)/);
  assert.match(js, /function pivotField\(pivot, args\)/);
  assert.match(js, /targetSortObject\(context, args\)/);
  assert.match(js, /sort\.apply\(sortFieldsFrom\(args\.fields\), Boolean\(args\.match_case\), args\.has_headers !== false/);
  assert.match(js, /table\.sort\.apply\(sortFieldsFrom\(args\.fields\), Boolean\(args\.match_case\), sortMethodFrom\(args\.method\)\)/);
  assert.match(js, /targetWorksheet\(context, args\)\.autoFilter/);
  assert.match(js, /autoFilter\.apply\(range, Number\(args\.column_index\), filterCriteriaFrom\(args\.criteria\)\)/);
  assert.match(js, /table\.columns\.getItem\(requiredString\(args, 'column', 'excel\.apply_filter requires column for table filters\.'\)\)\.filter\.apply\(filterCriteriaFrom\(args\.criteria\)\)/);
  assert.match(js, /excel\.read_range/);
  assert.match(js, /excel\.write_range/);
  assert.match(js, /excel\.add_sheet/);
  assert.match(js, /excel\.set_formula/);
  assert.match(js, /excel\.format_range/);
  assert.match(js, /excel\.create_table/);
  assert.match(js, /excel\.create_chart/);
  assert.match(js, /async function readRange/);
  const readRangeBody = functionBody(js, 'readRange');
  assert.match(readRangeBody, /args\.metadata_only/);
  assert.match(readRangeBody, /isNullObject/);
  assert.match(readRangeBody, /empty: true/);
  assert.match(readRangeBody, /args\.values_only/);
  assert.doesNotMatch(readRangeBody, /values_only: true/);
  const readRangeTargetBody = functionBody(js, 'readRangeTarget');
  assert.match(readRangeTargetBody, /optionalTrimmedString\(args\.address\)/);
  assert.match(readRangeTargetBody, /resolveRangeTarget\(context, args\)/);
  assert.match(readRangeTargetBody, /getUsedRangeOrNullObject\(true\)/);
  assert.match(js, /async function writeRange/);
  assert.match(js, /async function addSheet/);
  assert.match(js, /async function setFormula/);
  assert.match(js, /async function formatRange/);
  assert.match(js, /async function createTable/);
  assert.match(js, /async function createChart/);
  assert.match(js, /resolveRangeTarget\(context, args\)/);
  assert.match(js, /async function resolveNamedItemRange/);
  assert.match(js, /workbook\.names\.getItemOrNullObject\(address\)/);
  assert.match(js, /worksheet\.names\.getItemOrNullObject\(address\)/);
  assert.match(js, /range\.values = args\.values/);
  assert.match(js, /context\.workbook\.worksheets\.add/);
  assert.match(js, /range\.formulas = formulaMatrixFrom\(args, range\.rowCount, range\.columnCount\)/);
  assert.match(js, /range\.format\.font\.bold/);
  assert.match(js, /validateFormatRangeLayoutArgs\(args\)/);
  assert.match(js, /if \(args\.style !== undefined\) applyRangeStyle\(range, args\.style\)/);
  assert.match(js, /range\.format\.horizontalAlignment = alignmentFrom\(args\.horizontal_alignment, 'horizontal'/);
  assert.match(js, /range\.format\.verticalAlignment = alignmentFrom\(args\.vertical_alignment, 'vertical'/);
  assert.match(js, /range\.format\.wrapText = Boolean\(args\.wrap_text\)/);
  assert.match(js, /applyRangeMerge\(range, args\.merge\)/);
  assert.match(js, /applyRangeLayout\(range, args\)/);
  assert.match(js, /applyBorders\(range, args\.borders\)/);
  assert.match(js, /range\.format\.autofitColumns\(\)/);
  assert.match(js, /range\.format\.autofitRows\(\)/);
  assert.match(js, /requireRequirementSet\('ExcelApi', '1\.2', 'autofit formatting'\)/);
  assert.match(js, /requireRequirementSet\('ExcelApi', '1\.2', 'range layout formatting'\)/);
  assert.match(js, /requireRequirementSet\('ExcelApi', '1\.7', 'range style formatting'\)/);
  assert.match(js, /range\.numberFormat = matrixFromScalar/);
  assert.match(js, /range\.numberFormat = numberFormatMatrixFrom/);
  assert.match(js, /function workbookStyleNames\(styles\)/);
  assert.match(js, /function validateFormatRangeLayoutArgs\(args\)/);
  assert.match(js, /column_width_pt cannot be combined with autofit_columns/);
  assert.match(js, /row_height_pt cannot be combined with autofit_rows/);
  assert.match(js, /function applyRangeStyle\(range, style\)/);
  assert.match(js, /range\.style = requiredNonEmptyString\(style, 'excel\.format_range style must be a non-empty string\.'\)/);
  assert.match(js, /function applyRangeMerge\(range, value\)/);
  assert.match(js, /range\.merge\(false\)/);
  assert.match(js, /range\.merge\(true\)/);
  assert.match(js, /range\.unmerge\(\)/);
  assert.match(js, /function applyRangeLayout\(range, args\)/);
  assert.match(js, /range\.format\.columnWidth = Number\(args\.column_width_pt\)/);
  assert.match(js, /range\.format\.rowHeight = Number\(args\.row_height_pt\)/);
  assert.match(js, /range\.format\.columnHidden = Boolean\(args\.hidden_columns\)/);
  assert.match(js, /range\.format\.rowHidden = Boolean\(args\.hidden_rows\)/);
  assert.match(js, /function formulaMatrixFrom\(args, rows, columns\)/);
  assert.match(js, /function numberFormatMatrixFrom\(args, rows, columns\)/);
  assert.match(js, /validateMatrixShape\(args\.formulas, rows, columns, 'formulas'\)/);
  assert.match(js, /validateMatrixShape\(args\.number_formats, rows, columns, 'number_formats'\)/);
  assert.match(js, /function validateMatrixShape\(matrix, rows, columns, label\)/);
  assert.match(js, /officeMcpCode: 'HOST_CAPABILITY_UNAVAILABLE'/);
  assert.match(js, /function alignmentFrom\(value, axis\)/);
  assert.match(js, /function applyBorders\(range, borders\)/);
  assert.match(js, /range\.format\.borders\.getItem\(borderIndexFrom\(border\.side\)\)/);
  assert.match(js, /rangeBorder\.style = borderLineStyleFrom\(border\.style\)/);
  assert.match(js, /rangeBorder\.weight = borderWeightFrom\(border\.weight\)/);
  assert.match(js, /function borderIndexFrom\(value\)/);
  assert.match(js, /function borderLineStyleFrom\(value\)/);
  assert.match(js, /function borderWeightFrom\(value\)/);
  assert.match(js, /function sortFieldsFrom\(fields\)/);
  assert.match(js, /function filterCriteriaFrom\(criteria\)/);
  assert.match(js, /function filterOnFrom\(value\)/);
  assert.match(js, /function sortOrientationFrom\(value\)/);
  assert.match(js, /requireRequirementSet\('ExcelApi', '1\.9', 'range copy and autofill'\)/);
  assert.match(js, /destination\.copyFrom\(source, rangeCopyTypeFrom\(args\.copy_type\), Boolean\(args\.skip_blanks\), Boolean\(args\.transpose\)\)/);
  assert.match(js, /source\.autoFill\(destination, autoFillTypeFrom\(args\.autofill_type\)\)/);
  assert.match(js, /function validateCopyRangeArgs\(args\)/);
  assert.match(js, /function getDocumentProperties\(args\)/);
  assert.match(js, /function updateDocumentProperties\(args\)/);
  assert.match(js, /function validateUpdateDocumentPropertiesArgs\(tool, args\)/);
  assert.match(functionBody(js, 'validateUpdateDocumentPropertiesArgs'), /requires at least one writable property or custom operation/);
  assert.match(functionBody(js, 'updateDocumentProperties'), /custom_set/);
  assert.match(functionBody(js, 'updateDocumentProperties'), /custom_delete/);
  assert.match(functionBody(js, 'availableToolsForRequirements'), /ExcelApi_1_7[\s\S]*excel\.get_document_properties[\s\S]*excel\.update_document_properties/);
  assert.match(js, /function rangeCopyTypeFrom\(value\)/);
  assert.match(js, /function autoFillTypeFrom\(value\)/);
  assert.match(js, /function validateAutofillContainsSource\(source, destination\)/);
  assert.match(js, /context\.workbook\.tables\.add/);
  assert.match(js, /worksheet\.charts\.add/);
  assert.match(js, /function chartTypeFrom/);
  assert.match(js, /function requiredString/);
  assert.match(js, /INVALID_ARGUMENT/);
  assert.match(js, /Excel\.run/);
  assert.match(js, /OfficeCtlCommon/);
  assert.match(js, /OfficeCtlAddinChannel/);
  assert.match(js, /OfficeCtlLogger/);
  assert.match(js, /OfficeCtlTaskHistory/);
  assert.match(js, /window\.__OFFICE_MCP_TASKPANE_READY__ = true/);
  assert.match(js, /function whenOfficeReady\(callback\)/);
  assert.match(js, /!window\.Office \|\| typeof Office\.onReady !== 'function'/);
  assert.doesNotMatch(js, /const \{ completed \} = taskStore\.snapshot\(\)/);
  assert.doesNotMatch(js, /console\.(log|warn|error)/);
  assert.doesNotMatch(js, /method: 'register'/);
  assert.doesNotMatch(js, /method: 'session\.added'/);
});

test('Excel task pane routes mutating tools through validation-only preflight', () => {
  const js = readFileSync(join(ADDIN_ROOT, 'public', 'taskpane.js'), 'utf8');
  const invokeBody = functionBody(js, 'invokeTool');

  assert.match(js, /function validateExcelMutationOnly\(tool, args\)/);
  assert.match(invokeBody, /case 'excel\.add_sheet':\s*data = args\?\.validate_only \? await validateExcelMutationOnly\(tool, args\) : await addSheet\(args\);/);
  assert.match(invokeBody, /case 'excel\.save':\s*data = args\?\.validate_only \? await validateExcelMutationOnly\(tool, args\) : await saveWorkbook\(args\);/);
  assert.match(invokeBody, /case 'excel\.calculate':\s*data = args\?\.validate_only \? await validateExcelMutationOnly\(tool, args\) : await calculateWorkbook\(args\);/);
  assert.match(invokeBody, /case 'excel\.update_named_item':\s*data = args\?\.validate_only \? await validateExcelMutationOnly\(tool, args\) : await updateNamedItem\(args\);/);
  assert.match(invokeBody, /case 'excel\.update_document_properties':\s*data = args\?\.validate_only \? await validateExcelMutationOnly\(tool, args\) : await updateDocumentProperties\(args\);/);
  assert.match(invokeBody, /case 'excel\.write_range':\s*data = args\?\.validate_only \? await validateExcelMutationOnly\(tool, args\) : await writeRange\(args\);/);
  assert.match(invokeBody, /case 'excel\.insert_range':\s*data = args\?\.validate_only \? await validateExcelMutationOnly\(tool, args\) : await insertRange\(args\);/);
  assert.match(invokeBody, /case 'excel\.clear_range':\s*data = args\?\.validate_only \? await validateExcelMutationOnly\(tool, args\) : await clearRange\(args\);/);
  assert.match(invokeBody, /case 'excel\.set_hyperlink':\s*data = args\?\.validate_only \? await validateExcelMutationOnly\(tool, args\) : await setHyperlink\(args\);/);
  assert.match(invokeBody, /case 'excel\.set_data_validation':\s*data = args\?\.validate_only \? await validateExcelMutationOnly\(tool, args\) : await setDataValidation\(args\);/);
  assert.match(invokeBody, /case 'excel\.copy_range':\s*data = args\?\.validate_only \? await validateExcelMutationOnly\(tool, args\) : await copyRange\(args\);/);
  assert.match(invokeBody, /case 'excel\.update_conditional_format':\s*data = args\?\.validate_only \? await validateExcelMutationOnly\(tool, args\) : await updateConditionalFormat\(args\);/);
  assert.match(invokeBody, /case 'excel\.update_table':\s*data = args\?\.validate_only \? await validateExcelMutationOnly\(tool, args\) : await updateTable\(args\);/);
  assert.match(invokeBody, /case 'excel\.insert_image':\s*data = args\?\.validate_only \? await validateExcelMutationOnly\(tool, args\) : await insertImage\(args\);/);
  assert.match(invokeBody, /case 'excel\.update_shape':\s*data = args\?\.validate_only \? await validateExcelMutationOnly\(tool, args\) : await updateShape\(args\);/);
  assert.match(invokeBody, /case 'excel\.add_comment':\s*data = args\?\.validate_only \? await validateExcelMutationOnly\(tool, args\) : await addComment\(args\);/);
  assert.match(invokeBody, /case 'excel\.update_comment':\s*data = args\?\.validate_only \? await validateExcelMutationOnly\(tool, args\) : await updateComment\(args\);/);
  assert.match(functionBody(js, 'validateExcelMutationOnly'), /valid: true/);
  assert.match(functionBody(js, 'validateExcelMutationOnly'), /operation: tool/);
  assert.match(functionBody(js, 'validateExcelMutationOnly'), /partial_effect: 'none'/);
  assert.match(functionBody(js, 'validateExcelMutationOnly'), /resolved_target/);
});


test('Excel task pane keeps settings inline and compact at narrow widths', () => {
  const html = readFileSync(join(ADDIN_ROOT, 'public', 'taskpane.html'), 'utf8');
  const css = readFileSync(join(ADDIN_ROOT, '..', 'common', 'taskpane.css'), 'utf8');

  assert.match(css, /body \{[\s\S]*min-width: 320px;[\s\S]*overflow-x: hidden;/);
  assert.match(css, /\.taskpane-shell \{[\s\S]*align-content: start;[\s\S]*gap: 10px;[\s\S]*padding: 10px;/);
  assert.match(css, /\.summary-panel \{[\s\S]*display: grid;[\s\S]*gap: 10px;/);
  assert.match(css, /\.empty-state \{[\s\S]*padding: 10px;/);
  assert.match(css, /#documentTitle \{[\s\S]*display: -webkit-box;[\s\S]*-webkit-line-clamp: 2;/);
  assert.doesNotMatch(css, /\b(min-)?height:\s*(1[2-9]\d|[2-9]\d{2,})px/);
  assert.doesNotMatch(cssRule(css, '.summary-panel'), /\bheight:/);
  assert.doesNotMatch(cssRule(css, '.current-task-panel'), /\bheight:/);
  assert.doesNotMatch(cssRule(css, '.history-panel'), /\bheight:/);
  assert.doesNotMatch(css, /overflow-x:\s*(auto|scroll)/);

  const summaryStart = html.indexOf('class="panel summary-panel"');
  const documentMetadataIndex = html.indexOf('class="metadata-section document-metadata"');
  const daemonMetadataIndex = html.indexOf('class="metadata-section daemon-metadata"');
  const daemonFormIndex = html.indexOf('class="daemon-endpoint-form"');
  const sessionIndex = html.indexOf('data-copy-target="session"');
  const runtimeIndex = html.indexOf('id="runtimeVersions"');
  const currentTaskIndex = html.indexOf('id="currentTaskHeading"');
  assert.ok(summaryStart !== -1 && daemonFormIndex !== -1, 'summary and daemon form exist');
  assert.ok(documentMetadataIndex > summaryStart, 'document metadata is in the summary panel');
  assert.ok(daemonMetadataIndex > documentMetadataIndex, 'daemon metadata is separate from document metadata');
  assert.ok(daemonFormIndex > daemonMetadataIndex, 'daemon endpoint stays inside daemon metadata');
  assert.ok(runtimeIndex > daemonMetadataIndex, 'runtime versions stay inside daemon metadata');
  assert.ok(sessionIndex > daemonMetadataIndex, 'session id stays inside daemon metadata');
  assert.ok(daemonFormIndex < currentTaskIndex, 'daemon settings appear before current task');
  assert.doesNotMatch(html, /<section id="settingsPanel"/);
});
test('Excel task pane announces session only after successful register response', () => {
  const js = readFileSync(join(ADDIN_ROOT, 'public', 'taskpane.js'), 'utf8');
  const registerBody = functionBody(js, 'register');
  const responseBody = functionBody(js, 'handleRegisterResponse');
  const announceBody = functionBody(js, 'announceSession');

  assert.doesNotMatch(registerBody, /announceSession\(/);
  assert.match(responseBody, /serverInfo = registerResult\(message, PROTOCOL_VERSION\)/);
  assert.match(responseBody, /runtimeInstanceId = serverInfo\.assignedInstanceId \|\| instanceId/);
  assert.match(responseBody, /enableAutoOpen\(\)\.then\(\(\) => announceSession\(\)\)\.catch/);
  assert.match(responseBody, /session\.announce\.failed/);
  assert.match(announceBody, /instance_id: runtimeInstanceId/);
  assert.doesNotMatch(announceBody, /instance_id: instanceId/);
});

function functionBody(source, name) {
  const start = source.indexOf(`function ${name}(`);
  assert.notEqual(start, -1, `missing function ${name}`);
  const open = source.indexOf('{', start);
  let depth = 0;
  for (let index = open; index < source.length; index += 1) {
    if (source[index] === '{') depth += 1;
    if (source[index] === '}') depth -= 1;
    if (depth === 0) return source.slice(open + 1, index);
  }
  assert.fail(`unterminated function ${name}`);
}

function cssRule(source, selector) {
  const escaped = selector.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const match = source.match(new RegExp(`${escaped}\\s*\\{([\\s\\S]*?)\\}`));
  return match?.[1] || '';
}
